-- ============================================================
-- FILE: asop_schema.sql
-- DATABASE: PostgreSQL (с PostGIS)
-- ОПИСАНИЕ: Финальная схема БД АСОП.
--           - Разделение Маршрут (справочник) / Путь (физическое направление).
--           - Безопасность ПДн: Keycloak, хэширование и шифрование СНИЛС, M:N доступы.
--           - Справочники ФИАС/ГАР для регионов и территорий.
--           - Гибкие правила скидок и услуг (с необязательной привязкой к перевозчику, ТС, тарифу).
--           - Расширенная модель управления терминалами (профили, ПО, МОЛ, иерархия).
--           - IS_PRIMARY в ASOP_CARDS (одна основная карта на пользователя для льгот).
--           - ASOP_GPS_TRACKING (вместо ASOP_DISPATCH_POSITIONS).
--           - ASOP_PAYMENTS (таблица поступлений/пополнений на карту) с поддержкой Offline Top-Up.
--           - LAST_SYNC_RECEIPT_TIME (INT) в ASOP_CARDS для синхронизации с 32-битной памятью чипа MIFARE.
--           - НОВОЕ: ASOP_CARDS_DISTRIBUTORS (юрлица-дистрибьюторы карт).
--           - НОВОЕ: ASOP_CONTRACTS (общий справочник договоров с перевозчиками и дистрибьюторами).
--           - НОВОЕ: ASOP_DISTRIBUTOR_TERMINALS (платёжные терминалы дистрибьюторов).
-- ============================================================

CREATE EXTENSION IF NOT EXISTS postgis;

-- ========================
-- 0. РЕГИОНЫ И ТЕРРИТОРИИ (ФИАС/ГАР)
-- ========================

CREATE TABLE ASOP_REGIONS
(
    REGION_ID          UUID NOT NULL,
    MUNICIPAL_DIVISION VARCHAR(255),
    ADMIN_DIVISION     VARCHAR(255),
    FEDERAL_DISTRICT   VARCHAR(255),
    IFNS_FL_CODE       VARCHAR(4),
    IFNS_UL_CODE       VARCHAR(4),
    OKATO_CODE         VARCHAR(11),
    OKTMO_CODE         VARCHAR(11),
    OKTMO_BUDGET_CODE  VARCHAR(11),
    FIAS_ID            VARCHAR(36),
    REGISTRY_RECORD_ID VARCHAR(30),
    CONSTRAINT pk_regions PRIMARY KEY (REGION_ID),
    CONSTRAINT uq_regions_fias UNIQUE (FIAS_ID)
);
COMMENT ON TABLE ASOP_REGIONS IS 'Справочник регионов на основе данных ФИАС/ГАР.';

CREATE TABLE ASOP_TERRITORIES
(
    TERRITORY_ID       UUID NOT NULL,
    REGION_ID          UUID NOT NULL,
    MUNICIPAL_DIVISION VARCHAR(255),
    ADMIN_DIVISION     VARCHAR(255),
    FEDERAL_DISTRICT   VARCHAR(255),
    IFNS_FL_CODE       VARCHAR(4),
    IFNS_UL_CODE       VARCHAR(4),
    OKATO_CODE         VARCHAR(11),
    OKTMO_CODE         VARCHAR(11),
    OKTMO_BUDGET_CODE  VARCHAR(11),
    FIAS_ID            VARCHAR(36),
    REGISTRY_RECORD_ID VARCHAR(30),
    GEO_POLYGON        GEOGRAPHY(POLYGON, 4326),
    CONSTRAINT pk_territories PRIMARY KEY (TERRITORY_ID),
    CONSTRAINT fk_territory_region FOREIGN KEY (REGION_ID) REFERENCES ASOP_REGIONS (REGION_ID),
    CONSTRAINT uq_territories_fias UNIQUE (FIAS_ID)
);
COMMENT ON TABLE ASOP_TERRITORIES IS 'Административно-территориальные единицы с гео-полигонами и реквизитами ФИАС.';
CREATE INDEX idx_territories_geo ON ASOP_TERRITORIES USING GIST (GEO_POLYGON);

CREATE TABLE ASOP_ORGANIZERS
(
    ORGANIZER_ID   UUID         NOT NULL,
    ORGANIZER_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_organizers PRIMARY KEY (ORGANIZER_ID)
);
COMMENT ON TABLE ASOP_ORGANIZERS IS 'Организаторы перевозок.';

CREATE TABLE ASOP_ORGANIZER_TERRITORIES
(
    ORGANIZER_ID UUID NOT NULL,
    TERRITORY_ID UUID NOT NULL,
    CONSTRAINT pk_organizer_territories PRIMARY KEY (ORGANIZER_ID, TERRITORY_ID),
    CONSTRAINT fk_ot_organizer FOREIGN KEY (ORGANIZER_ID) REFERENCES ASOP_ORGANIZERS (ORGANIZER_ID),
    CONSTRAINT fk_ot_territory FOREIGN KEY (TERRITORY_ID) REFERENCES ASOP_TERRITORIES (TERRITORY_ID)
);
COMMENT ON TABLE ASOP_ORGANIZER_TERRITORIES IS 'Связь Многие-ко-многим: Организаторы <-> Территории.';

-- ========================
-- 1. СПРАВОЧНИКИ
-- ========================

CREATE TABLE ASOP_ROLES
(
    ROLE_ID   UUID         NOT NULL,
    ROLE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (ROLE_ID)
);

CREATE TABLE ASOP_CARD_TYPES
(
    CARD_TYPE_ID   UUID         NOT NULL,
    CARD_TYPE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_card_types PRIMARY KEY (CARD_TYPE_ID)
);

CREATE TABLE ASOP_TARIFF_TYPES
(
    TARIFF_TYPE_ID UUID         NOT NULL,
    CODE           VARCHAR(50)  NOT NULL,
    NAME           VARCHAR(100) NOT NULL,
    DESCRIPTION    TEXT,
    CONSTRAINT pk_tariff_types PRIMARY KEY (TARIFF_TYPE_ID),
    CONSTRAINT uq_tariff_types_code UNIQUE (CODE)
);

CREATE TABLE ASOP_SESSION_TYPES
(
    SESSION_TYPE_ID   UUID         NOT NULL,
    SESSION_TYPE_CODE VARCHAR(30)  NOT NULL,
    SESSION_TYPE_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT pk_session_types PRIMARY KEY (SESSION_TYPE_ID),
    CONSTRAINT uq_session_types_code UNIQUE (SESSION_TYPE_CODE)
);

CREATE TABLE ASOP_EVENT_TYPES
(
    EVENT_TYPE      CHAR(4)      NOT NULL,
    EVENT_TYPE_NAME VARCHAR(128) NOT NULL,
    CONSTRAINT pk_event_types PRIMARY KEY (EVENT_TYPE)
);

CREATE TABLE ASOP_TRANSACTION_TYPES
(
    TRANSACTION_TYPE_ID   UUID         NOT NULL,
    TRANSACTION_TYPE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_transaction_types PRIMARY KEY (TRANSACTION_TYPE_ID)
);

CREATE TABLE ASOP_TRANSACTION_RESULTS
(
    TRANSACTION_RESULT_ID   UUID         NOT NULL,
    TRANSACTION_RESULT_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_transaction_results PRIMARY KEY (TRANSACTION_RESULT_ID)
);

CREATE TABLE ASOP_SERVICES
(
    SERVICE_ID   UUID         NOT NULL,
    SERVICE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION  TEXT,
    PRIORITY     INT          NOT NULL UNIQUE,
    REGION_ID    UUID         NOT NULL,
    CONSTRAINT pk_services PRIMARY KEY (SERVICE_ID),
    CONSTRAINT fk_services_region FOREIGN KEY (REGION_ID) REFERENCES ASOP_REGIONS (REGION_ID)
);
COMMENT ON TABLE ASOP_SERVICES IS 'Классификатор платных услуг ("Услуга" в чеке).';

-- Льготы вынесены сюда, т.к. на них ссылаются маршруты (ASOP_PATH_BENEFITS)
CREATE TABLE ASOP_BENEFITS
(
    BENEFIT_ID   UUID         NOT NULL,
    BENEFIT_CODE VARCHAR(50)  NOT NULL,
    BENEFIT_NAME VARCHAR(100) NOT NULL,
    REGION_CODE  VARCHAR(50)  NOT NULL,
    DESCRIPTION  TEXT,
    IS_ACTIVE    BOOLEAN DEFAULT true,
    CREATED_AT   TIMESTAMP    NOT NULL,
    UPDATED_AT   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_benefits PRIMARY KEY (BENEFIT_ID),
    CONSTRAINT uq_benefits_code UNIQUE (BENEFIT_CODE)
);

CREATE TABLE ASOP_BENEFIT_STEPS
(
    STEP_ID             UUID          NOT NULL,
    BENEFIT_ID          UUID          NOT NULL,
    STEP_ORDER          INT           NOT NULL,
    TRIP_THRESHOLD_FROM INT           NOT NULL DEFAULT 0,
    TRIP_THRESHOLD_TO   INT,
    DISCOUNT_SHARE      NUMERIC(4, 2) NOT NULL CHECK (DISCOUNT_SHARE BETWEEN 0 AND 1),
    PERIOD_TYPE         VARCHAR(20)   NOT NULL DEFAULT 'MONTHLY',
    CONSTRAINT pk_benefit_steps PRIMARY KEY (STEP_ID),
    CONSTRAINT fk_steps_benefit FOREIGN KEY (BENEFIT_ID) REFERENCES ASOP_BENEFITS (BENEFIT_ID) ON DELETE CASCADE,
    CONSTRAINT uq_benefit_steps_order UNIQUE (BENEFIT_ID, STEP_ORDER),
    CONSTRAINT chk_steps_range CHECK (TRIP_THRESHOLD_TO IS NULL OR TRIP_THRESHOLD_TO > TRIP_THRESHOLD_FROM)
);

-- ========================
-- 1.1. ДИСТРИБЬЮТОРЫ КАРТ (НОВОЕ)
-- ========================

CREATE TABLE ASOP_CARDS_DISTRIBUTORS
(
    CARDS_DISTRIBUTOR_ID UUID         NOT NULL,
    DISTRIBUTOR_NAME     VARCHAR(255) NOT NULL,
    INN                  VARCHAR(12)  NOT NULL,
    KPP                  VARCHAR(9),
    LEGAL_ADDRESS        VARCHAR(500),
    CONTACT_PHONE        VARCHAR(20),
    CONTACT_EMAIL        VARCHAR(100),
    IS_ACTIVE            BOOLEAN      DEFAULT true,
    CREATED_AT           TIMESTAMP    NOT NULL,
    UPDATED_AT           TIMESTAMP    NOT NULL,
    CONSTRAINT pk_cards_distributors PRIMARY KEY (CARDS_DISTRIBUTOR_ID),
    CONSTRAINT uq_cards_distributors_inn UNIQUE (INN)
);
COMMENT ON TABLE ASOP_CARDS_DISTRIBUTORS IS 'Юрлица-дистрибьюторы карт, которые могут пополнять MIFARE-карты через свои платёжные терминалы.';
CREATE INDEX idx_cards_distributors_active ON ASOP_CARDS_DISTRIBUTORS (IS_ACTIVE) WHERE IS_ACTIVE = true;

-- ========================
-- 2. ПЕРЕВОЗЧИКИ, ДОГОВОРЫ И ТС
-- ========================

CREATE TABLE ASOP_CARRIERS
(
    CARRIER_ID   UUID         NOT NULL,
    CARRIER_NAME VARCHAR(255) NOT NULL,
    INN          VARCHAR(12)  NOT NULL,
    REGION_ID    UUID         NOT NULL,
    CONSTRAINT pk_carriers PRIMARY KEY (CARRIER_ID),
    CONSTRAINT uq_carriers_inn UNIQUE (INN),
    CONSTRAINT fk_carriers_region FOREIGN KEY (REGION_ID) REFERENCES ASOP_REGIONS (REGION_ID)
);

-- Общий справочник договоров (НОВОЕ, заменяет ASOP_CARRIER_CONTRACTS)
CREATE TABLE ASOP_CONTRACTS
(
    CONTRACT_ID            UUID         NOT NULL,
    CONTRACTOR_TYPE        VARCHAR(20)  NOT NULL CHECK (CONTRACTOR_TYPE IN ('CARRIER', 'CARDS_DISTRIBUTOR')),
    CARRIER_ID             UUID,
    CARDS_DISTRIBUTOR_ID   UUID,
    CONTRACT_NUMBER        VARCHAR(100) NOT NULL,
    START_DATE             DATE         NOT NULL,
    END_DATE               DATE,
    STATUS                 VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'SUSPENDED', 'TERMINATED')),
    COMMISSION_PERCENT     NUMERIC(5, 2),
    CREATED_AT             TIMESTAMP    NOT NULL,
    UPDATED_AT             TIMESTAMP    NOT NULL,
    CONSTRAINT pk_contracts PRIMARY KEY (CONTRACT_ID),
    CONSTRAINT fk_contracts_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_contracts_cards_distributor FOREIGN KEY (CARDS_DISTRIBUTOR_ID) REFERENCES ASOP_CARDS_DISTRIBUTORS (CARDS_DISTRIBUTOR_ID),
    CONSTRAINT chk_contracts_contractor CHECK (
        (CONTRACTOR_TYPE = 'CARRIER' AND CARRIER_ID IS NOT NULL AND CARDS_DISTRIBUTOR_ID IS NULL) OR
        (CONTRACTOR_TYPE = 'CARDS_DISTRIBUTOR' AND CARDS_DISTRIBUTOR_ID IS NOT NULL AND CARRIER_ID IS NULL)
    )
);
COMMENT ON TABLE ASOP_CONTRACTS IS 'Общий справочник договоров с контрагентами (перевозчиками или дистрибьюторами карт).';
CREATE INDEX idx_contracts_carrier ON ASOP_CONTRACTS (CARRIER_ID) WHERE CARRIER_ID IS NOT NULL;
CREATE INDEX idx_contracts_cards_distributor ON ASOP_CONTRACTS (CARDS_DISTRIBUTOR_ID) WHERE CARDS_DISTRIBUTOR_ID IS NOT NULL;
CREATE INDEX idx_contracts_status ON ASOP_CONTRACTS (STATUS);

CREATE TABLE ASOP_CONTRACT_ROUTES
(
    CONTRACT_ID UUID NOT NULL,
    ROUTE_ID    UUID NOT NULL,
    CONSTRAINT pk_contract_routes PRIMARY KEY (CONTRACT_ID, ROUTE_ID),
    CONSTRAINT fk_cr_contract FOREIGN KEY (CONTRACT_ID) REFERENCES ASOP_CONTRACTS (CONTRACT_ID),
    CONSTRAINT fk_cr_route FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID)
);

CREATE TABLE ASOP_VEHICLE_TYPES
(
    VEHICLE_TYPE_ID UUID         NOT NULL,
    TYPE_NAME       VARCHAR(100) NOT NULL,
    CONSTRAINT pk_vehicle_types PRIMARY KEY (VEHICLE_TYPE_ID)
);

CREATE TABLE ASOP_VEHICLE_MODELS
(
    VEHICLE_MODEL_ID UUID         NOT NULL,
    MODEL_NAME       VARCHAR(255) NOT NULL,
    CONSTRAINT pk_vehicle_models PRIMARY KEY (VEHICLE_MODEL_ID)
);

CREATE TABLE ASOP_VEHICLES
(
    VEHICLE_ID       UUID         NOT NULL,
    CARRIER_ID       UUID         NOT NULL,
    VEHICLE_TYPE_ID  UUID         NOT NULL,
    VEHICLE_MODEL_ID UUID         NOT NULL,
    VEHICLE_NUMBER   VARCHAR(16)  NOT NULL,
    VEHICLE_NAME     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_vehicles PRIMARY KEY (VEHICLE_ID),
    CONSTRAINT fk_vehicles_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_vehicles_type FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES ASOP_VEHICLE_TYPES (VEHICLE_TYPE_ID),
    CONSTRAINT fk_vehicles_model FOREIGN KEY (VEHICLE_MODEL_ID) REFERENCES ASOP_VEHICLE_MODELS (VEHICLE_MODEL_ID)
);

-- ========================
-- 3. ПОЛЬЗОВАТЕЛИ И БЕЗОПАСНОСТЬ (Keycloak + ПДн)
-- ========================

CREATE TABLE ASOP_USERS
(
    USER_ID            UUID         NOT NULL,
    FIRST_NAME         VARCHAR(100) NOT NULL,
    LAST_NAME_INITIAL  CHAR(1)      NOT NULL,
    PATRONYMIC_INITIAL CHAR(1),
    PHONE              VARCHAR(20),
    SNILS_HASH         VARCHAR(64) UNIQUE,
    SNILS_ENCRYPTED    BYTEA,
    KEYCLOAK_ID        VARCHAR(255) UNIQUE,
    CONSTRAINT pk_users PRIMARY KEY (USER_ID)
);
COMMENT ON TABLE ASOP_USERS IS 'ПДн защищены: СНИЛС хэшируется и шифруется, ФИО сокращено, аутентификация через Keycloak. Пустые M:N таблицы = доступ ко всем.';

CREATE TABLE ASOP_USER_ROLES
(
    USER_ID UUID NOT NULL,
    ROLE_ID UUID NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT fk_ur_user FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID),
    CONSTRAINT fk_ur_role FOREIGN KEY (ROLE_ID) REFERENCES ASOP_ROLES (ROLE_ID)
);

CREATE TABLE ASOP_USER_CARRIERS
(
    USER_ID    UUID NOT NULL,
    CARRIER_ID UUID NOT NULL,
    CONSTRAINT pk_user_carriers PRIMARY KEY (USER_ID, CARRIER_ID),
    CONSTRAINT fk_uc_user FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID),
    CONSTRAINT fk_uc_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID)
);

CREATE TABLE ASOP_USER_REGIONS
(
    USER_ID   UUID NOT NULL,
    REGION_ID UUID NOT NULL,
    CONSTRAINT pk_user_regions PRIMARY KEY (USER_ID, REGION_ID),
    CONSTRAINT fk_ureg_user FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID),
    CONSTRAINT fk_ureg_region FOREIGN KEY (REGION_ID) REFERENCES ASOP_REGIONS (REGION_ID)
);

-- ========================
-- 4. МАРШРУТЫ И ПУТИ
-- ========================

CREATE TABLE ASOP_FARE_ZONES
(
    ZONE_ID      UUID         NOT NULL,
    ZONE_CODE    VARCHAR(20)  NOT NULL,
    ZONE_NAME    VARCHAR(100) NOT NULL,
    DESCRIPTION  VARCHAR(256),
    ZONE_POLYGON GEOGRAPHY(POLYGON, 4326),
    REGION_ID    UUID         NOT NULL,
    CONSTRAINT pk_fare_zones PRIMARY KEY (ZONE_ID),
    CONSTRAINT uq_fare_zones_code UNIQUE (ZONE_CODE),
    CONSTRAINT fk_fare_zones_region FOREIGN KEY (REGION_ID) REFERENCES ASOP_REGIONS (REGION_ID),
    CONSTRAINT chk_fare_zones_valid_polygon CHECK (ZONE_POLYGON IS NULL OR ST_IsValid(ZONE_POLYGON))
);

CREATE TABLE ASOP_TRANSPORT_STOPS
(
    STOP_ID      UUID         NOT NULL,
    FARE_ZONE_ID UUID,
    STOP_CODE    VARCHAR(20)  NOT NULL,
    STOP_NAME    VARCHAR(200) NOT NULL,
    STOP_ADDRESS VARCHAR(500),
    ZONE_POLYGON GEOGRAPHY(POLYGON, 4326),
    DESCRIPTION  TEXT,
    IS_ACTIVE    BOOLEAN DEFAULT true,
    CREATED_AT   TIMESTAMP    NOT NULL,
    UPDATED_AT   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_transport_stops PRIMARY KEY (STOP_ID),
    CONSTRAINT uq_stop_code UNIQUE (STOP_CODE),
    CONSTRAINT fk_transport_stops_zone_id FOREIGN KEY (FARE_ZONE_ID) REFERENCES ASOP_FARE_ZONES (ZONE_ID)
);
CREATE INDEX idx_transport_stops_geo ON ASOP_TRANSPORT_STOPS USING GIST (ZONE_POLYGON);

CREATE TABLE ASOP_ROUTES
(
    ROUTE_ID             UUID         NOT NULL,
    ROUTE_NUMBER         VARCHAR(50)  NOT NULL,
    ROUTE_NAME           VARCHAR(255) NOT NULL,
    ORGANIZER_ID         UUID,
    MINISTRY_REGISTRY_NO VARCHAR(50),
    ROUTE_CATEGORY       VARCHAR(30) CHECK (ROUTE_CATEGORY IN ('CITY', 'SUBURBAN', 'INTERCITY', 'EXPRESS')),
    REGION_ID            UUID         NOT NULL,
    CONSTRAINT pk_routes PRIMARY KEY (ROUTE_ID),
    CONSTRAINT fk_routes_organizer FOREIGN KEY (ORGANIZER_ID) REFERENCES ASOP_ORGANIZERS (ORGANIZER_ID),
    CONSTRAINT fk_routes_region FOREIGN KEY (REGION_ID) REFERENCES ASOP_REGIONS (REGION_ID)
);
COMMENT ON TABLE ASOP_ROUTES IS 'Справочник маршрутов (номер, название, категория).';

CREATE TABLE ASOP_PATHS
(
    PATH_ID         UUID         NOT NULL,
    ROUTE_ID        UUID         NOT NULL,
    PATH_NAME       VARCHAR(100) NOT NULL,
    START_STOP_ID   UUID,
    END_STOP_ID     UUID,
    ROUTE_OBJECT    JSONB,
    BENEFIT_POLICY  VARCHAR(20)  NOT NULL DEFAULT 'ALL' CHECK (BENEFIT_POLICY IN ('ALL', 'ALLOWLIST', 'NONE')),
    PATH_START_DATE TIMESTAMP,
    PATH_END_DATE   TIMESTAMP,
    DESCRIPTION     VARCHAR(512),
    REGION_ID       UUID         NOT NULL,
    CONSTRAINT pk_paths PRIMARY KEY (PATH_ID),
    CONSTRAINT fk_paths_route FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID),
    CONSTRAINT fk_paths_start_stop FOREIGN KEY (START_STOP_ID) REFERENCES ASOP_TRANSPORT_STOPS (STOP_ID),
    CONSTRAINT fk_paths_end_stop FOREIGN KEY (END_STOP_ID) REFERENCES ASOP_TRANSPORT_STOPS (STOP_ID),
    CONSTRAINT fk_paths_region FOREIGN KEY (REGION_ID) REFERENCES ASOP_REGIONS (REGION_ID),
    CONSTRAINT chk_paths_valid_dates CHECK (PATH_START_DATE IS NULL OR PATH_END_DATE IS NULL OR
                                            PATH_END_DATE > PATH_START_DATE)
);
COMMENT ON TABLE ASOP_PATHS IS 'Физические пути (направления) маршрута с начальной и конечной остановками.';

CREATE TABLE ASOP_PATH_TRANSPORT_STOPS
(
    PATH_STOP_ID  UUID      NOT NULL,
    PATH_ID       UUID      NOT NULL,
    STOP_ID       UUID      NOT NULL,
    SERIAL_NUMBER INT       NOT NULL,
    CREATED_AT    TIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP NOT NULL,
    CONSTRAINT pk_path_transport_stops PRIMARY KEY (PATH_STOP_ID),
    CONSTRAINT fk_pts_path FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID),
    CONSTRAINT fk_pts_stop FOREIGN KEY (STOP_ID) REFERENCES ASOP_TRANSPORT_STOPS (STOP_ID)
);
CREATE UNIQUE INDEX uk_path_transport_stops ON ASOP_PATH_TRANSPORT_STOPS (PATH_ID, STOP_ID);

CREATE TABLE ASOP_SCHEDULE
(
    SCHEDULE_ID    UUID NOT NULL,
    PATH_ID        UUID NOT NULL,
    STOP_ID        UUID NOT NULL,
    DAY_MASK       INT  NOT NULL DEFAULT 127,
    ARRIVAL_TIME   TIME NOT NULL,
    DWELL_TIME_SEC INT           DEFAULT 30,
    IS_ACTIVE      BOOLEAN       DEFAULT true,
    CONSTRAINT pk_schedule PRIMARY KEY (SCHEDULE_ID),
    CONSTRAINT fk_sched_path FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID) ON DELETE CASCADE,
    CONSTRAINT fk_sched_stop FOREIGN KEY (STOP_ID) REFERENCES ASOP_TRANSPORT_STOPS (STOP_ID),
    CONSTRAINT chk_day_mask CHECK (DAY_MASK BETWEEN 1 AND 127)
);

CREATE TABLE ASOP_PATH_SERVICES
(
    PATH_SERVICE_ID UUID           NOT NULL,
    PATH_ID         UUID           NOT NULL,
    SERVICE_ID      UUID           NOT NULL,
    CARRIER_ID      UUID,
    VEHICLE_ID      UUID,
    TARIFF_TYPE_ID  UUID,
    PRICE           NUMERIC(10, 2) NOT NULL,
    IS_ACTIVE       BOOLEAN DEFAULT true,
    CONSTRAINT pk_path_services PRIMARY KEY (PATH_SERVICE_ID),
    CONSTRAINT fk_ps_path FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID) ON DELETE CASCADE,
    CONSTRAINT fk_ps_service FOREIGN KEY (SERVICE_ID) REFERENCES ASOP_SERVICES (SERVICE_ID),
    CONSTRAINT fk_ps_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_ps_vehicle FOREIGN KEY (VEHICLE_ID) REFERENCES ASOP_VEHICLES (VEHICLE_ID),
    CONSTRAINT fk_ps_tariff FOREIGN KEY (TARIFF_TYPE_ID) REFERENCES ASOP_TARIFF_TYPES (TARIFF_TYPE_ID),
    CONSTRAINT uq_path_service UNIQUE (PATH_ID, SERVICE_ID, CARRIER_ID, VEHICLE_ID, TARIFF_TYPE_ID)
);
COMMENT ON TABLE ASOP_PATH_SERVICES IS 'Дополнительные услуги на пути. Цена и доступность могут зависеть от перевозчика, ТС или тарифа.';

CREATE TABLE ASOP_PATH_DISCOUNTS
(
    PATH_DISCOUNT_ID UUID           NOT NULL,
    PATH_ID          UUID           NOT NULL,
    CARRIER_ID       UUID,
    VEHICLE_ID       UUID,
    TARIFF_TYPE_ID   UUID,
    DISCOUNT_NAME    VARCHAR(100)   NOT NULL,
    DISCOUNT_TYPE    VARCHAR(20)    NOT NULL DEFAULT 'PERCENT' CHECK (DISCOUNT_TYPE IN ('PERCENT', 'FIXED')),
    DISCOUNT_VALUE   NUMERIC(10, 2) NOT NULL CHECK (DISCOUNT_VALUE >= 0),
    VALID_FROM       TIMESTAMP      NOT NULL,
    VALID_UNTIL      TIMESTAMP,
    IS_ACTIVE        BOOLEAN                 DEFAULT true,
    CONSTRAINT pk_path_discounts PRIMARY KEY (PATH_DISCOUNT_ID),
    CONSTRAINT fk_pd_path FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID) ON DELETE CASCADE,
    CONSTRAINT fk_pd_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_pd_vehicle FOREIGN KEY (VEHICLE_ID) REFERENCES ASOP_VEHICLES (VEHICLE_ID),
    CONSTRAINT fk_pd_tariff FOREIGN KEY (TARIFF_TYPE_ID) REFERENCES ASOP_TARIFF_TYPES (TARIFF_TYPE_ID)
);
COMMENT ON TABLE ASOP_PATH_DISCOUNTS IS 'Скидки на пути. Поддерживает фиксированные суммы и проценты, может быть уточнена по перевозчику, ТС или тарифу.';

CREATE TABLE ASOP_PATH_BENEFITS
(
    PATH_BENEFIT_ID UUID NOT NULL,
    PATH_ID         UUID NOT NULL,
    BENEFIT_ID      UUID NOT NULL,
    CONSTRAINT pk_path_benefits PRIMARY KEY (PATH_BENEFIT_ID),
    CONSTRAINT fk_pb_path FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID) ON DELETE CASCADE,
    CONSTRAINT fk_pb_benefit FOREIGN KEY (BENEFIT_ID) REFERENCES ASOP_BENEFITS (BENEFIT_ID) ON DELETE CASCADE,
    CONSTRAINT uq_path_benefit UNIQUE (PATH_ID, BENEFIT_ID)
);

-- ========================
-- 5. КАРТЫ, ЛЬГОТЫ, ТАРИФЫ
-- ========================

CREATE TABLE ASOP_CARDS
(
    CARD_ID                UUID      NOT NULL,
    CARD_TYPE_ID           UUID      NOT NULL,
    USER_ID                UUID,
    IS_PRIMARY             BOOLEAN DEFAULT false,
    LAST_SYNC_RECEIPT_TIME INT     DEFAULT 0,
    REGISTERED_AT          TIMESTAMP,
    REGISTERED_BY_USER_ID  UUID,
    CREATED_AT             TIMESTAMP NOT NULL,
    UPDATED_AT             TIMESTAMP NOT NULL,
    CONSTRAINT pk_cards PRIMARY KEY (CARD_ID),
    CONSTRAINT fk_cards_type_id FOREIGN KEY (CARD_TYPE_ID) REFERENCES ASOP_CARD_TYPES (CARD_TYPE_ID),
    CONSTRAINT fk_cards_user_id FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID)
);
COMMENT ON COLUMN ASOP_CARDS.IS_PRIMARY IS 'У одного пользователя может быть только одна карта с этим флагом = true (обеспечивается частичным уникальным индексом).';
COMMENT ON COLUMN ASOP_CARDS.LAST_SYNC_RECEIPT_TIME IS 'Значение RECEIPT_UNIX_TIME (INT) последнего платежа, успешно записанного на физическую карту. Тип INT выбран для соответствия 32-битной структуре данных чипа MIFARE.';
CREATE UNIQUE INDEX uk_user_primary_card ON ASOP_CARDS (USER_ID) WHERE IS_PRIMARY = true AND USER_ID IS NOT NULL;

CREATE TABLE ASOP_CARD_MIFARES
(
    CARD_ID          UUID  NOT NULL,
    UID              BYTEA NOT NULL,
    ATQA             SMALLINT,
    SAK              SMALLINT,
    PROTOCOL_VERSION INT,
    MEMORY_MAP       JSONB,
    CONSTRAINT pk_card_mifares PRIMARY KEY (CARD_ID),
    CONSTRAINT uq_mifare_uid UNIQUE (UID),
    CONSTRAINT fk_mifares_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID) ON DELETE CASCADE
);

CREATE TABLE ASOP_CARD_BANKS
(
    CARD_ID      UUID         NOT NULL,
    PAN_TOKEN    VARCHAR(256) NOT NULL,
    PAN_LAST4    CHAR(4),
    BIN          CHAR(6),
    IS_TOKENIZED BOOLEAN DEFAULT false,
    CONSTRAINT pk_card_banks PRIMARY KEY (CARD_ID),
    CONSTRAINT fk_banks_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID) ON DELETE CASCADE
);

CREATE TABLE ASOP_CARD_TARIFFS
(
    CARD_TARIFF_ID          UUID      NOT NULL,
    CARD_ID                 UUID      NOT NULL,
    TARIFF_TYPE_ID          UUID      NOT NULL,
    BALANCE                 NUMERIC(10, 2),
    TRAVEL_COUNT            INT,
    MAX_TRAVEL_COUNT        INT,
    EXPIRATION_DATE         TIMESTAMP,
    ACTIVATED_AT            TIMESTAMP,
    PURCHASE_TRANSACTION_ID UUID,
    IS_ACTIVE               BOOLEAN DEFAULT true,
    CREATED_AT              TIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP NOT NULL,
    CONSTRAINT pk_card_tariffs PRIMARY KEY (CARD_TARIFF_ID),
    CONSTRAINT fk_card_tariffs_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID) ON DELETE CASCADE,
    CONSTRAINT fk_card_tariffs_type FOREIGN KEY (TARIFF_TYPE_ID) REFERENCES ASOP_TARIFF_TYPES (TARIFF_TYPE_ID)
);

CREATE TABLE ASOP_BLACKLISTS
(
    CARD_ID    UUID        NOT NULL,
    BLOCK_TYPE VARCHAR(20) NOT NULL,
    BLOCKED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_blacklists PRIMARY KEY (CARD_ID),
    CONSTRAINT fk_blacklists_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID),
    CONSTRAINT chk_blacklist_type CHECK (BLOCK_TYPE IN ('PERMANENT', 'NEGATIVE_BALANCE'))
);

CREATE TABLE ASOP_USER_BENEFITS
(
    ASSIGNMENT_ID UUID      NOT NULL,
    USER_ID       UUID      NOT NULL,
    BENEFIT_ID    UUID      NOT NULL,
    VALID_FROM    TIMESTAMP NOT NULL,
    VALID_UNTIL   TIMESTAMP,
    SYNC_VERSION  INT       NOT NULL DEFAULT 1,
    CREATED_AT    TIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP NOT NULL,
    CONSTRAINT pk_user_benefits PRIMARY KEY (ASSIGNMENT_ID),
    CONSTRAINT fk_ub_user FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT fk_ub_benefit FOREIGN KEY (BENEFIT_ID) REFERENCES ASOP_BENEFITS (BENEFIT_ID)
);

CREATE TABLE ASOP_TARIFF_RATES
(
    TARIFF_RATE_ID UUID           NOT NULL,
    TARIFF_TYPE_ID UUID           NOT NULL,
    CARRIER_ID     UUID,
    ZONE_ID        UUID,
    PATH_ID        UUID,
    PRICE          NUMERIC(10, 2) NOT NULL,
    DESCRIPTION    TEXT,
    IS_ACTIVE      BOOLEAN DEFAULT true,
    CREATED_AT     TIMESTAMP      NOT NULL,
    UPDATED_AT     TIMESTAMP      NOT NULL,
    CONSTRAINT pk_tariff_rates PRIMARY KEY (TARIFF_RATE_ID),
    CONSTRAINT fk_tariff_rates_type FOREIGN KEY (TARIFF_TYPE_ID) REFERENCES ASOP_TARIFF_TYPES (TARIFF_TYPE_ID),
    CONSTRAINT fk_tariff_rates_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_tariff_rates_zone FOREIGN KEY (ZONE_ID) REFERENCES ASOP_FARE_ZONES (ZONE_ID),
    CONSTRAINT fk_tariff_rates_path FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID)
);

-- ========================
-- 6. ОБОРУДОВАНИЕ: ТЕРМИНАЛЫ, TID, ПРОФИЛИ, ПО
-- ========================

CREATE TABLE ASOP_TERMINAL_PROFILES
(
    PROFILE_ID     UUID         NOT NULL,
    PROFILE_NAME   VARCHAR(100) NOT NULL,
    PROFILE_PARAMS JSONB,
    CONSTRAINT pk_terminal_profiles PRIMARY KEY (PROFILE_ID),
    CONSTRAINT uq_terminal_profiles_name UNIQUE (PROFILE_NAME)
);
COMMENT ON TABLE ASOP_TERMINAL_PROFILES IS 'Справочник профилей настроек терминалов.';

CREATE TABLE ASOP_TERMINAL_SOFTWARE
(
    SOFTWARE_VERSION_ID UUID         NOT NULL,
    TERMINAL_TYPE       VARCHAR(100) NOT NULL,
    VERSION             VARCHAR(100) NOT NULL,
    FILE_PATH           VARCHAR(500),
    UPDATE_DATE         TIMESTAMP    NOT NULL,
    CONSTRAINT pk_terminal_software PRIMARY KEY (SOFTWARE_VERSION_ID)
);
COMMENT ON TABLE ASOP_TERMINAL_SOFTWARE IS 'Справочник версий программного обеспечения терминалов.';

-- НОВОЕ: Платёжные терминалы дистрибьюторов карт
CREATE TABLE ASOP_DISTRIBUTOR_TERMINALS
(
    DISTRIBUTOR_TERMINAL_ID UUID         NOT NULL,
    CARDS_DISTRIBUTOR_ID    UUID         NOT NULL,
    CONTRACT_ID             UUID,
    TERMINAL_NUMBER         VARCHAR(16)  NOT NULL,
    TERMINAL_SERIAL         VARCHAR(64)  NOT NULL,
    TERMINAL_MODEL          VARCHAR(100),
    PAYMENT_PROVIDER_ID     VARCHAR(100) NOT NULL,
    STATUS                  VARCHAR(50)  NOT NULL DEFAULT 'WAREHOUSE' CHECK (STATUS IN ('WAREHOUSE', 'ISSUED', 'ACTIVE', 'SUSPENDED', 'DECOMMISSIONED')),
    MOL_USER_ID             UUID,
    PROFILE_ID              UUID,
    SOFTWARE_VERSION_ID     UUID,
    CREATED_AT              TIMESTAMP    NOT NULL,
    UPDATED_AT              TIMESTAMP    NOT NULL,
    CONSTRAINT pk_distributor_terminals PRIMARY KEY (DISTRIBUTOR_TERMINAL_ID),
    CONSTRAINT fk_distributor_terminals_distributor FOREIGN KEY (CARDS_DISTRIBUTOR_ID) REFERENCES ASOP_CARDS_DISTRIBUTORS (CARDS_DISTRIBUTOR_ID),
    CONSTRAINT fk_distributor_terminals_contract FOREIGN KEY (CONTRACT_ID) REFERENCES ASOP_CONTRACTS (CONTRACT_ID),
    CONSTRAINT fk_distributor_terminals_mol FOREIGN KEY (MOL_USER_ID) REFERENCES ASOP_USERS (USER_ID),
    CONSTRAINT fk_distributor_terminals_profile FOREIGN KEY (PROFILE_ID) REFERENCES ASOP_TERMINAL_PROFILES (PROFILE_ID),
    CONSTRAINT fk_distributor_terminals_software FOREIGN KEY (SOFTWARE_VERSION_ID) REFERENCES ASOP_TERMINAL_SOFTWARE (SOFTWARE_VERSION_ID),
    CONSTRAINT uq_distributor_terminals_provider_id UNIQUE (PAYMENT_PROVIDER_ID)
);
COMMENT ON TABLE ASOP_DISTRIBUTOR_TERMINALS IS 'Платёжные терминалы дистрибьюторов карт для пополнения MIFARE-карт. Имеют те же связи, что и транспортные терминалы (профиль, ПО, МОЛ).';
COMMENT ON COLUMN ASOP_DISTRIBUTOR_TERMINALS.PAYMENT_PROVIDER_ID IS 'Уникальный идентификатор терминала в платёжной системе дистрибьютора.';
CREATE INDEX idx_distributor_terminals_distributor ON ASOP_DISTRIBUTOR_TERMINALS (CARDS_DISTRIBUTOR_ID);
CREATE INDEX idx_distributor_terminals_contract ON ASOP_DISTRIBUTOR_TERMINALS (CONTRACT_ID) WHERE CONTRACT_ID IS NOT NULL;
CREATE INDEX idx_distributor_terminals_status ON ASOP_DISTRIBUTOR_TERMINALS (STATUS);

CREATE TABLE ASOP_TIDS
(
    TID_ID        UUID        NOT NULL,
    CARRIER_ID    UUID        NOT NULL,
    TERMINAL_ID   UUID,
    TID_VALUE     VARCHAR(20) NOT NULL,
    STATUS        VARCHAR(20) DEFAULT 'UNUSED',
    ASSIGNED_AT   TIMESTAMP,
    UNASSIGNED_AT TIMESTAMP,
    CREATED_AT    TIMESTAMP   NOT NULL,
    UPDATED_AT    TIMESTAMP   NOT NULL,
    CONSTRAINT pk_tids PRIMARY KEY (TID_ID),
    CONSTRAINT fk_tids_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_tids_terminal FOREIGN KEY (TERMINAL_ID) REFERENCES ASOP_TERMINALS (TERMINAL_ID),
    CONSTRAINT uq_tids_value UNIQUE (TID_VALUE),
    CONSTRAINT chk_tid_status CHECK (STATUS IN ('UNUSED', 'ASSIGNED', 'REVOKED'))
);
COMMENT ON TABLE ASOP_TIDS IS 'Пул TID. 1:N к перевозчику. Привязка к терминалу происходит в рейсе (сессии) или напрямую.';

CREATE TABLE ASOP_TERMINALS
(
    TERMINAL_ID           UUID        NOT NULL,
    CARRIER_ID            UUID,
    TERMINAL_NUMBER       VARCHAR(16) NOT NULL,
    TERMINAL_SERIAL       VARCHAR(64) NOT NULL,
    TERMINAL_MODEL        VARCHAR(100),
    STATUS                VARCHAR(50) DEFAULT 'WAREHOUSE',
    MOL_USER_ID           UUID,
    PARENT_TERMINAL_ID    UUID,
    TID_ID                UUID,
    VEHICLE_ID            UUID,
    PROFILE_ID            UUID,
    SOFTWARE_VERSION_ID   UUID,
    BENEFITS_SYNC_TOKEN   VARCHAR(64),
    LAST_BENEFITS_SYNC_AT TIMESTAMP,
    CONSTRAINT pk_terminals PRIMARY KEY (TERMINAL_ID),
    CONSTRAINT fk_terminals_carrier_id FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_terminals_mol FOREIGN KEY (MOL_USER_ID) REFERENCES ASOP_USERS (USER_ID),
    CONSTRAINT fk_terminals_parent FOREIGN KEY (PARENT_TERMINAL_ID) REFERENCES ASOP_TERMINALS (TERMINAL_ID),
    CONSTRAINT fk_terminals_tid FOREIGN KEY (TID_ID) REFERENCES ASOP_TIDS (TID_ID),
    CONSTRAINT fk_terminals_vehicle FOREIGN KEY (VEHICLE_ID) REFERENCES ASOP_VEHICLES (VEHICLE_ID),
    CONSTRAINT fk_terminals_profile FOREIGN KEY (PROFILE_ID) REFERENCES ASOP_TERMINAL_PROFILES (PROFILE_ID),
    CONSTRAINT fk_terminals_software FOREIGN KEY (SOFTWARE_VERSION_ID) REFERENCES ASOP_TERMINAL_SOFTWARE (SOFTWARE_VERSION_ID)
);
COMMENT ON TABLE ASOP_TERMINALS IS 'Терминалы оплаты и валидаторы. Связь с ТС — через это поле (исторически) и через сессию-рейс.';
CREATE INDEX idx_terminals_carrier ON ASOP_TERMINALS (CARRIER_ID);
CREATE INDEX idx_terminals_vehicle ON ASOP_TERMINALS (VEHICLE_ID);
CREATE INDEX idx_terminals_status ON ASOP_TERMINALS (STATUS);

-- ========================
-- 7. СЕССИИ, ТРАНЗАКЦИИ, АУДИТ, КРС
-- ========================

CREATE TABLE ASOP_SESSIONS
(
    SESSION_ID        UUID      NOT NULL,
    SESSION_TYPE_ID   UUID      NOT NULL,
    PARENT_SESSION_ID UUID,
    TERMINAL_ID       UUID,
    TID_ID            UUID,
    OPENED_BY_USER_ID UUID,
    CLOSED_BY_USER_ID UUID,
    CARD_ID           UUID,
    PATH_ID           UUID,
    VEHICLE_ID        UUID,
    STARTED_AT        TIMESTAMP NOT NULL,
    CLOSED_AT         TIMESTAMP,
    STARTED_AT_LOCAL  TIMESTAMP NOT NULL,
    CLOSED_AT_LOCAL   TIMESTAMP,
    EXPIRATION_TIME   TIMESTAMP NOT NULL,
    STATUS            VARCHAR(20) DEFAULT 'IN_PROGRESS' CHECK (STATUS IN
                                                               ('IN_PROGRESS', 'CLOSED', 'CANCELLED', 'CONFIRMED',
                                                                'NOT_CONFIRMED')),
    ATTRIBUTES        JSONB,
    CONSTRAINT pk_sessions PRIMARY KEY (SESSION_ID),
    CONSTRAINT fk_sessions_type FOREIGN KEY (SESSION_TYPE_ID) REFERENCES ASOP_SESSION_TYPES (SESSION_TYPE_ID),
    CONSTRAINT fk_sessions_parent FOREIGN KEY (PARENT_SESSION_ID) REFERENCES ASOP_SESSIONS (SESSION_ID) ON DELETE SET NULL,
    CONSTRAINT fk_sessions_terminal_id FOREIGN KEY (TERMINAL_ID) REFERENCES ASOP_TERMINALS (TERMINAL_ID),
    CONSTRAINT fk_sessions_tid_id FOREIGN KEY (TID_ID) REFERENCES ASOP_TIDS (TID_ID),
    CONSTRAINT fk_sessions_opened_by FOREIGN KEY (OPENED_BY_USER_ID) REFERENCES ASOP_USERS (USER_ID) ON DELETE SET NULL,
    CONSTRAINT fk_sessions_closed_by FOREIGN KEY (CLOSED_BY_USER_ID) REFERENCES ASOP_USERS (USER_ID) ON DELETE SET NULL,
    CONSTRAINT fk_sessions_card_id FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID),
    CONSTRAINT fk_sessions_path_id FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID),
    CONSTRAINT fk_sessions_vehicle_id FOREIGN KEY (VEHICLE_ID) REFERENCES ASOP_VEHICLES (VEHICLE_ID)
);
COMMENT ON TABLE ASOP_SESSIONS IS 'Иерархические сессии. Привязаны к PATH_ID (конкретному пути). ATTRIBUTES хранит контекст.';
CREATE INDEX idx_sessions_parent ON ASOP_SESSIONS (PARENT_SESSION_ID);
CREATE INDEX idx_sessions_type_status ON ASOP_SESSIONS (SESSION_TYPE_ID, STATUS);
CREATE INDEX idx_sessions_terminal ON ASOP_SESSIONS (TERMINAL_ID);
CREATE INDEX idx_sessions_tid ON ASOP_SESSIONS (TID_ID);
CREATE INDEX idx_sessions_path ON ASOP_SESSIONS (PATH_ID);

-- КРС Workflow
CREATE TABLE ASOP_AUDIT_SERVICES
(
    AUDIT_SERVICE_ID UUID         NOT NULL,
    SERVICE_CODE     VARCHAR(50)  NOT NULL,
    SERVICE_NAME     VARCHAR(255) NOT NULL,
    ISSUER_TYPE      VARCHAR(20)  NOT NULL CHECK (ISSUER_TYPE IN ('ORGANIZER', 'CARRIER')),
    ORGANIZER_ID     UUID,
    CARRIER_ID       UUID,
    IS_ACTIVE        BOOLEAN DEFAULT true,
    CREATED_AT       TIMESTAMP    NOT NULL,
    UPDATED_AT       TIMESTAMP    NOT NULL,
    CONSTRAINT pk_audit_services PRIMARY KEY (AUDIT_SERVICE_ID),
    CONSTRAINT fk_audit_service_organizer FOREIGN KEY (ORGANIZER_ID) REFERENCES ASOP_ORGANIZERS (ORGANIZER_ID),
    CONSTRAINT fk_audit_service_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT uq_audit_service_code UNIQUE (SERVICE_CODE),
    CONSTRAINT chk_audit_service_issuer CHECK ((ISSUER_TYPE = 'ORGANIZER' AND ORGANIZER_ID IS NOT NULL AND
                                                CARRIER_ID IS NULL) OR
                                               (ISSUER_TYPE = 'CARRIER' AND CARRIER_ID IS NOT NULL AND ORGANIZER_ID IS NULL))
);

CREATE TABLE ASOP_AUDIT_TASKS
(
    TASK_ID                   UUID        NOT NULL,
    TASK_NUMBER               VARCHAR(50) NOT NULL,
    ISSUER_TYPE               VARCHAR(20) NOT NULL CHECK (ISSUER_TYPE IN ('ORGANIZER', 'CARRIER')),
    ORGANIZER_ID              UUID,
    CARRIER_ID                UUID,
    ASSIGNED_AUDIT_SERVICE_ID UUID        NOT NULL,
    TASK_START_DATE           TIMESTAMP   NOT NULL,
    TASK_END_DATE             TIMESTAMP,
    STATUS                    VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (STATUS IN ('DRAFT', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    DESCRIPTION               TEXT,
    CREATED_AT                TIMESTAMP   NOT NULL,
    UPDATED_AT                TIMESTAMP   NOT NULL,
    CONSTRAINT pk_audit_tasks PRIMARY KEY (TASK_ID),
    CONSTRAINT fk_task_organizer FOREIGN KEY (ORGANIZER_ID) REFERENCES ASOP_ORGANIZERS (ORGANIZER_ID),
    CONSTRAINT fk_task_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_task_service FOREIGN KEY (ASSIGNED_AUDIT_SERVICE_ID) REFERENCES ASOP_AUDIT_SERVICES (AUDIT_SERVICE_ID)
);

CREATE TABLE ASOP_AUDIT_TASK_PATHS
(
    TASK_PATH_ID UUID NOT NULL,
    TASK_ID      UUID NOT NULL,
    PATH_ID      UUID NOT NULL,
    CONSTRAINT pk_audit_task_paths PRIMARY KEY (TASK_PATH_ID),
    CONSTRAINT fk_atp_task FOREIGN KEY (TASK_ID) REFERENCES ASOP_AUDIT_TASKS (TASK_ID) ON DELETE CASCADE,
    CONSTRAINT fk_atp_path FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID),
    CONSTRAINT uq_task_path UNIQUE (TASK_ID, PATH_ID)
);

CREATE TABLE ASOP_AUDIT_BRIGADES
(
    BRIGADE_ID      UUID        NOT NULL,
    TASK_ID         UUID        NOT NULL,
    FOREMAN_USER_ID UUID,
    BRIGADE_STATUS  VARCHAR(20) NOT NULL DEFAULT 'FORMING' CHECK (BRIGADE_STATUS IN ('FORMING', 'ACTIVE', 'COMPLETED', 'CANCELLED')),
    STARTED_AT      TIMESTAMP,
    CLOSED_AT       TIMESTAMP,
    CREATED_AT      TIMESTAMP   NOT NULL,
    UPDATED_AT      TIMESTAMP   NOT NULL,
    CONSTRAINT pk_audit_brigades PRIMARY KEY (BRIGADE_ID),
    CONSTRAINT fk_brigade_task FOREIGN KEY (TASK_ID) REFERENCES ASOP_AUDIT_TASKS (TASK_ID),
    CONSTRAINT fk_brigade_foreman FOREIGN KEY (FOREMAN_USER_ID) REFERENCES ASOP_USERS (USER_ID) ON DELETE SET NULL
);

CREATE TABLE ASOP_AUDIT_BRIGADE_MEMBERS
(
    MEMBER_ID  UUID        NOT NULL,
    BRIGADE_ID UUID        NOT NULL,
    USER_ID    UUID        NOT NULL,
    ROLE       VARCHAR(20) NOT NULL CHECK (ROLE IN ('FOREMAN', 'CONTROLLER')),
    CONSTRAINT pk_audit_brigade_members PRIMARY KEY (MEMBER_ID),
    CONSTRAINT fk_abm_brigade FOREIGN KEY (BRIGADE_ID) REFERENCES ASOP_AUDIT_BRIGADES (BRIGADE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_abm_user FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID),
    CONSTRAINT uq_brigade_member UNIQUE (BRIGADE_ID, USER_ID)
);

CREATE TABLE ASOP_AUDIT_INSPECTIONS
(
    INSPECTION_ID          UUID        NOT NULL,
    BRIGADE_ID             UUID        NOT NULL,
    CONTROLLER_SESSION_ID  UUID        NOT NULL,
    PATH_ID                UUID,
    INSPECTION_START       TIMESTAMP   NOT NULL,
    INSPECTION_END         TIMESTAMP,
    DURATION INTERVAL,
    PATH_NAME              VARCHAR(255),
    PASSENGERS_CHECKED     INT                  DEFAULT 0,
    PASSENGERS_PAID        INT                  DEFAULT 0,
    PASSENGERS_COMPENSATED INT                  DEFAULT 0,
    PASSENGERS_UNPAID      INT                  DEFAULT 0,
    FINES_COUNT            INT                  DEFAULT 0,
    STATUS                 VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (STATUS IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED')),
    CREATED_AT             TIMESTAMP   NOT NULL,
    UPDATED_AT             TIMESTAMP   NOT NULL,
    CONSTRAINT pk_audit_inspections PRIMARY KEY (INSPECTION_ID),
    CONSTRAINT fk_inspection_brigade FOREIGN KEY (BRIGADE_ID) REFERENCES ASOP_AUDIT_BRIGADES (BRIGADE_ID),
    CONSTRAINT fk_inspection_session FOREIGN KEY (CONTROLLER_SESSION_ID) REFERENCES ASOP_SESSIONS (SESSION_ID),
    CONSTRAINT fk_inspection_path FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID)
);
COMMENT ON TABLE ASOP_AUDIT_INSPECTIONS IS 'Акты проверок. Данные о ТС/терминале/пути вытягиваются из CONTROLLER_SESSION_ID.';

CREATE TABLE ASOP_AUDIT_INSPECTION_TASKS
(
    INSPECTION_TASK_ID UUID NOT NULL,
    INSPECTION_ID      UUID NOT NULL,
    TASK_ID            UUID NOT NULL,
    CONSTRAINT pk_audit_inspection_tasks PRIMARY KEY (INSPECTION_TASK_ID),
    CONSTRAINT fk_ait_inspection FOREIGN KEY (INSPECTION_ID) REFERENCES ASOP_AUDIT_INSPECTIONS (INSPECTION_ID) ON DELETE CASCADE,
    CONSTRAINT fk_ait_task FOREIGN KEY (TASK_ID) REFERENCES ASOP_AUDIT_TASKS (TASK_ID),
    CONSTRAINT uq_inspection_task UNIQUE (INSPECTION_ID, TASK_ID)
);
COMMENT ON TABLE ASOP_AUDIT_INSPECTION_TASKS IS 'Связь M2M: одна инспекция может быть проведена по нескольким заданиям КРС.';

CREATE TABLE ASOP_TRANSACTIONS
(
    TRANSACTION_ID        UUID           NOT NULL,
    STARTED_AT            TIMESTAMP      NOT NULL,
    COMPLETED_AT          TIMESTAMP,
    SESSION_ID            UUID,
    TRANSACTION_TYPE_ID   UUID           NOT NULL,
    TRANSACTION_RESULT_ID UUID           NOT NULL,
    AMOUNT                NUMERIC(10, 2) NOT NULL DEFAULT 0,
    CURRENCY              CHAR(3)                 DEFAULT 'RUB',
    ACQUIRER_REFERENCE    VARCHAR(128),
    ERROR_CODE            VARCHAR(50),
    ERROR_MESSAGE         VARCHAR(512),
    METADATA              JSONB,
    CONSTRAINT pk_transactions PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT fk_transactions_session FOREIGN KEY (SESSION_ID) REFERENCES ASOP_SESSIONS (SESSION_ID),
    CONSTRAINT fk_transactions_type FOREIGN KEY (TRANSACTION_TYPE_ID) REFERENCES ASOP_TRANSACTION_TYPES (TRANSACTION_TYPE_ID),
    CONSTRAINT fk_transactions_result FOREIGN KEY (TRANSACTION_RESULT_ID) REFERENCES ASOP_TRANSACTION_RESULTS (TRANSACTION_RESULT_ID)
);
COMMENT ON TABLE ASOP_TRANSACTIONS IS 'Финансовые проводки (списания). METADATA хранит детали расчета (зоны, скидки, льготы).';
CREATE INDEX idx_transactions_session ON ASOP_TRANSACTIONS (SESSION_ID);
CREATE INDEX idx_transactions_completed_at ON ASOP_TRANSACTIONS (COMPLETED_AT) WHERE COMPLETED_AT IS NULL;

CREATE TABLE ASOP_TRANSACTION_CARDS
(
    TRANSACTION_CARD_ID UUID        NOT NULL,
    TRANSACTION_ID      UUID        NOT NULL,
    CARD_ID             UUID        NOT NULL,
    CARD_ROLE           VARCHAR(20) NOT NULL,
    TARIFF_APPLIED_ID   UUID,
    BALANCE_BEFORE      NUMERIC(10, 2),
    BALANCE_AFTER       NUMERIC(10, 2),
    CONSTRAINT pk_transaction_cards PRIMARY KEY (TRANSACTION_CARD_ID),
    CONSTRAINT fk_tc_transaction FOREIGN KEY (TRANSACTION_ID) REFERENCES ASOP_TRANSACTIONS (TRANSACTION_ID) ON DELETE CASCADE,
    CONSTRAINT fk_tc_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID),
    CONSTRAINT fk_tc_tariff FOREIGN KEY (TARIFF_APPLIED_ID) REFERENCES ASOP_CARD_TARIFFS (CARD_TARIFF_ID)
);
CREATE UNIQUE INDEX uk_transaction_cards_main ON ASOP_TRANSACTION_CARDS (TRANSACTION_ID, CARD_ID);

-- Поступления (пополнения) на карту с поддержкой Offline Top-Up
CREATE TABLE ASOP_PAYMENTS
(
    PAYMENT_ID               UUID        NOT NULL,
    CARD_ID                  UUID        NOT NULL,
    RECEIPT_UNIX_TIME        INT         NOT NULL,
    SESSION_ID               UUID,
    EVENT_ID                 UUID,
    USER_ID                  UUID,
    DISTRIBUTOR_TERMINAL_ID  UUID,
    AMOUNT                   NUMERIC(10, 2)       DEFAULT 0,
    TRIPS_ADDED              INT                  DEFAULT 0,
    PAYMENT_METHOD           VARCHAR(50),
    STATUS                   VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'APPLIED', 'FAILED', 'REFUNDED')),
    EXTERNAL_REF             VARCHAR(128),
    CREATED_AT               TIMESTAMP   NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT fk_payments_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID),
    CONSTRAINT fk_payments_session FOREIGN KEY (SESSION_ID) REFERENCES ASOP_SESSIONS (SESSION_ID),
    CONSTRAINT fk_payments_event FOREIGN KEY (EVENT_ID) REFERENCES ASOP_EVENTS (EVENT_ID),
    CONSTRAINT fk_payments_user FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID),
    CONSTRAINT fk_payments_distributor_terminal FOREIGN KEY (DISTRIBUTOR_TERMINAL_ID) REFERENCES ASOP_DISTRIBUTOR_TERMINALS (DISTRIBUTOR_TERMINAL_ID)
);
COMMENT ON TABLE ASOP_PAYMENTS IS 'Поступления (пополнения) на карту: деньги или поездки. Связана с картой, опционально с сессией, событием, пользователем и платёжным терминалом дистрибьютора.';
COMMENT ON COLUMN ASOP_PAYMENTS.DISTRIBUTOR_TERMINAL_ID IS 'Ссылка на платёжный терминал дистрибьютора (если пополнение произошло через терминал, а не онлайн или в транспорте).';
CREATE INDEX idx_payments_card_sync ON ASOP_PAYMENTS (CARD_ID, RECEIPT_UNIX_TIME);
CREATE INDEX idx_payments_status ON ASOP_PAYMENTS (STATUS);
CREATE INDEX idx_payments_distributor_terminal ON ASOP_PAYMENTS (DISTRIBUTOR_TERMINAL_ID) WHERE DISTRIBUTOR_TERMINAL_ID IS NOT NULL;

CREATE TABLE ASOP_GPS_TRACKING
(
    POSITION_ID UUID      NOT NULL,
    VEHICLE_ID  UUID      NOT NULL,
    PATH_ID     UUID      NOT NULL,
    SESSION_ID  UUID,
    GPS_COORD   GEOGRAPHY(POINT, 4326),
    RECORDED_AT TIMESTAMP NOT NULL,
    SPEED_KMH   NUMERIC(5, 2),
    STATUS      VARCHAR(30) DEFAULT 'MOVING',
    CONSTRAINT pk_gps_tracking PRIMARY KEY (POSITION_ID),
    CONSTRAINT fk_gps_vehicle FOREIGN KEY (VEHICLE_ID) REFERENCES ASOP_VEHICLES (VEHICLE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_gps_path FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID),
    CONSTRAINT fk_gps_session FOREIGN KEY (SESSION_ID) REFERENCES ASOP_SESSIONS (SESSION_ID)
);
COMMENT ON TABLE ASOP_GPS_TRACKING IS 'GPS-трекинг транспорта (поток координат).';
CREATE INDEX idx_gps_vehicle_time ON ASOP_GPS_TRACKING (VEHICLE_ID, RECORDED_AT DESC);
CREATE INDEX idx_gps_geo ON ASOP_GPS_TRACKING USING GIST (GPS_COORD);

CREATE TABLE ASOP_EVENTS
(
    EVENT_ID          UUID      NOT NULL,
    EVENT_TIME        TIMESTAMP NOT NULL,
    EVENT_LOCAL_TIME  TIMESTAMP NOT NULL,
    EVENT_TYPE        CHAR(4)   NOT NULL,
    USER_ID           UUID,
    SESSION_ID        UUID,
    REFERENCE_TYPE_ID INT,
    REFERENCE_ID      UUID,
    EVENT_DETAILS     VARCHAR(256),
    EVENT_OBJECT      JSONB,
    CONSTRAINT pk_events PRIMARY KEY (EVENT_ID),
    CONSTRAINT fk_events_type FOREIGN KEY (EVENT_TYPE) REFERENCES ASOP_EVENT_TYPES (EVENT_TYPE),
    CONSTRAINT fk_events_session_id FOREIGN KEY (SESSION_ID) REFERENCES ASOP_SESSIONS (SESSION_ID),
    CONSTRAINT fk_events_user_id FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID)
);

-- ========================
-- 8. ОТЛОЖЕННЫЕ ВНЕШНИЕ КЛЮЧИ И ИНДЕКСЫ
-- ========================

-- FK для PURCHASE_TRANSACTION_ID (ASOP_TRANSACTIONS создаётся позже ASOP_CARD_TARIFFS)
ALTER TABLE ASOP_CARD_TARIFFS
    ADD CONSTRAINT fk_tariff_purchase FOREIGN KEY (PURCHASE_TRANSACTION_ID) REFERENCES ASOP_TRANSACTIONS (TRANSACTION_ID);

CREATE INDEX idx_users_keycloak ON ASOP_USERS (KEYCLOAK_ID) WHERE KEYCLOAK_ID IS NOT NULL;
CREATE INDEX idx_blacklists_type ON ASOP_BLACKLISTS (BLOCK_TYPE);
CREATE INDEX idx_card_tariffs_expiry ON ASOP_CARD_TARIFFS (EXPIRATION_DATE) WHERE IS_ACTIVE = true;
CREATE INDEX idx_sched_path_stop ON ASOP_SCHEDULE (PATH_ID, STOP_ID);
CREATE INDEX idx_sched_time ON ASOP_SCHEDULE (ARRIVAL_TIME);

COMMENT ON TABLE ASOP_ROUTES IS 'Справочник маршрутов (номер, название, категория).';
COMMENT ON TABLE ASOP_PATHS IS 'Физические пути маршрута (прямой/обратный) с начальной и конечной остановками.';
COMMENT ON TABLE ASOP_REGIONS IS 'Справочник регионов на основе данных ФИАС/ГАР.';