-- ============================================================
-- FILE: asop_schema.sql
-- DATABASE: TAVRIDA (PostgreSQL)
-- ОПИСАНИЕ: Схема БД АСОП. Префикс ASOP_, множественное число, UPPER_CASE
--           Все PK: UUID (генерируются на app-уровне)
-- ============================================================

CREATE
EXTENSION IF NOT EXISTS postgis;

-- ========================
-- 1. СПРАВОЧНИКИ
-- ========================

CREATE TABLE ASOP_ROLES
(
    ROLE_ID   UUID         NOT NULL,
    ROLE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (ROLE_ID)
);
COMMENT
ON TABLE ASOP_ROLES IS 'Роли доступа в системе.';
INSERT INTO ASOP_ROLES
VALUES (gen_random_uuid(), 'Администратор'),
       (gen_random_uuid(), 'Кассир'),
       (gen_random_uuid(), 'Водитель'),
       (gen_random_uuid(), 'Диспетчер'),
       (gen_random_uuid(), 'Контролер'),
       (gen_random_uuid(), 'Ревизор');

CREATE TABLE ASOP_CARD_TYPES
(
    CARD_TYPE_ID   UUID         NOT NULL,
    CARD_TYPE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_card_types PRIMARY KEY (CARD_TYPE_ID)
);
COMMENT
ON TABLE ASOP_CARD_TYPES IS 'Типы провозных носителей.';
INSERT INTO ASOP_CARD_TYPES
VALUES (gen_random_uuid(), 'MIFARE DESFire EV3'),
       (gen_random_uuid(), 'Bank Card (EMV)');

CREATE TABLE ASOP_TARIFF_TYPES
(
    TARIFF_TYPE_ID UUID         NOT NULL,
    CODE           VARCHAR(50)  NOT NULL,
    NAME           VARCHAR(100) NOT NULL,
    DESCRIPTION    TEXT,
    CONSTRAINT pk_tariff_types PRIMARY KEY (TARIFF_TYPE_ID),
    CONSTRAINT uq_tariff_types_code UNIQUE (CODE)
);
INSERT INTO ASOP_TARIFF_TYPES
VALUES (gen_random_uuid(), 'RIDES_PACKAGE', 'Пакет поездок', '...'),
       (gen_random_uuid(), 'UNLIMITED_TILL_DATE', 'Безлимит', '...'),
       (gen_random_uuid(), 'WALLET', 'Кошелёк', '...');

CREATE TABLE ASOP_EVENT_TYPES
(
    EVENT_TYPE      CHAR(4)      NOT NULL,
    EVENT_TYPE_NAME VARCHAR(128) NOT NULL,
    CONSTRAINT pk_event_types PRIMARY KEY (EVENT_TYPE)
);
INSERT INTO ASOP_EVENT_TYPES
VALUES ('CUSR', 'Создание пользователя'),
       ('CCRD', 'Создание карты'),
       ('TPAY', 'Оплата проезда'),
       ('SOPN', 'Открытие сессии'),
       ('SCLS', 'Закрытие сессии');

CREATE TABLE ASOP_TRANSACTION_TYPES
(
    TRANSACTION_TYPE_ID   UUID         NOT NULL,
    TRANSACTION_TYPE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_transaction_types PRIMARY KEY (TRANSACTION_TYPE_ID)
);
INSERT INTO ASOP_TRANSACTION_TYPES
VALUES (gen_random_uuid(), 'Пополнение'),
       (gen_random_uuid(), 'Списание');

CREATE TABLE ASOP_TRANSACTION_RESULTS
(
    TRANSACTION_RESULT_ID   UUID         NOT NULL,
    TRANSACTION_RESULT_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_transaction_results PRIMARY KEY (TRANSACTION_RESULT_ID)
);
INSERT INTO ASOP_TRANSACTION_RESULTS
VALUES (gen_random_uuid(), 'Успех'),
       (gen_random_uuid(), 'Ошибка - недостаточно средств'),
       (gen_random_uuid(), 'Ошибка - карта заблокирована');

CREATE TABLE ASOP_ROUTE_TYPES
(
    ROUTE_TYPE_ID   UUID        NOT NULL,
    ROUTE_TYPE_NAME VARCHAR(16) NOT NULL,
    CONSTRAINT pk_route_types PRIMARY KEY (ROUTE_TYPE_ID)
);
INSERT INTO ASOP_ROUTE_TYPES
VALUES (gen_random_uuid(), 'Маршрут'),
       (gen_random_uuid(), 'Путь');

CREATE TABLE ASOP_ORGANIZERS
(
    ORGANIZER_ID   UUID         NOT NULL,
    ORGANIZER_NAME VARCHAR(255) NOT NULL,
    REGION_CODE    VARCHAR(50),
    CREATED_AT     TIMESTAMP    NOT NULL,
    CONSTRAINT pk_organizers PRIMARY KEY (ORGANIZER_ID)
);
COMMENT
ON TABLE ASOP_ORGANIZERS IS 'Организаторы перевозок.';

CREATE TABLE ASOP_TERRITORIES
(
    TERRITORY_ID       UUID         NOT NULL,
    TERRITORY_NAME     VARCHAR(255) NOT NULL,
    CADASTRAL_NUMBER   VARCHAR(50),
    FIAS_CODE          VARCHAR(50),
    ORGANIZER_ID       UUID,
    IS_DISPATCH_ACTIVE BOOLEAN DEFAULT true,
    CONSTRAINT pk_territories PRIMARY KEY (TERRITORY_ID),
    CONSTRAINT fk_territory_organizer FOREIGN KEY (ORGANIZER_ID) REFERENCES ASOP_ORGANIZERS (ORGANIZER_ID)
);
COMMENT
ON TABLE ASOP_TERRITORIES IS 'Административно-территориальные единицы.';

CREATE TABLE ASOP_SERVICES
(
    SERVICE_ID      UUID         NOT NULL,
    SERVICE_CODE    VARCHAR(20)  NOT NULL,
    SERVICE_NAME    VARCHAR(100) NOT NULL,
    DESCRIPTION     TEXT,
    IS_DEFAULT      BOOLEAN DEFAULT false,
    ALLOW_DISCOUNTS BOOLEAN DEFAULT false,
    ALLOW_BENEFITS  BOOLEAN DEFAULT false,
    USE_ZONES       BOOLEAN DEFAULT false,
    PRIORITY        INT     DEFAULT 0,
    ROUTES_LIMIT    INT,
    CREATED_AT      TIMESTAMP    NOT NULL,
    CONSTRAINT pk_services PRIMARY KEY (SERVICE_ID),
    CONSTRAINT uq_services_code UNIQUE (SERVICE_CODE)
);
COMMENT
ON TABLE ASOP_SERVICES IS 'Классификатор платных услуг.';
INSERT INTO ASOP_SERVICES (SERVICE_ID, SERVICE_CODE, SERVICE_NAME, IS_DEFAULT, CREATED_AT)
VALUES (gen_random_uuid(), 'RIDE', 'Проезд', true, NOW()),
       (gen_random_uuid(), 'CHILD', 'Детский', false, NOW()),
       (gen_random_uuid(), 'LUGGAGE', 'Багаж', false, NOW());

CREATE TABLE ASOP_FARE_ZONES
(
    ZONE_ID      UUID         NOT NULL,
    ZONE_CODE    VARCHAR(20)  NOT NULL,
    ZONE_NAME    VARCHAR(100) NOT NULL,
    DESCRIPTION  VARCHAR(256),
    ZONE_POLYGON GEOGRAPHY(POLYGON, 4326),
    CONSTRAINT pk_fare_zones PRIMARY KEY (ZONE_ID),
    CONSTRAINT uq_fare_zones_code UNIQUE (ZONE_CODE),
    CONSTRAINT chk_fare_zones_valid_polygon CHECK (ZONE_POLYGON IS NULL OR ST_IsValid(ZONE_POLYGON))
);
CREATE INDEX idx_fare_zones_geo ON ASOP_FARE_ZONES USING GIST (ZONE_POLYGON);

CREATE TABLE ASOP_TRAVEL_ZONES
(
    TRAVEL_ZONE_ID   UUID         NOT NULL,
    FARE_ZONE_ID     UUID         NOT NULL,
    TRAVEL_ZONE_CODE VARCHAR(30)  NOT NULL,
    TRAVEL_ZONE_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT pk_travel_zones PRIMARY KEY (TRAVEL_ZONE_ID),
    CONSTRAINT fk_travel_zone_fare FOREIGN KEY (FARE_ZONE_ID) REFERENCES ASOP_FARE_ZONES (ZONE_ID),
    CONSTRAINT uq_travel_zones_code UNIQUE (TRAVEL_ZONE_CODE)
);
COMMENT
ON TABLE ASOP_TRAVEL_ZONES IS 'Зоны проезда внутри тарифных зон.';

CREATE TABLE ASOP_DISPATCH_POINTS
(
    DISPATCH_POINT_ID UUID         NOT NULL,
    TERRITORY_ID      UUID         NOT NULL,
    POINT_NAME        VARCHAR(255) NOT NULL,
    GEO_LOCATION      GEOGRAPHY(POINT, 4326),
    CONTACT_PHONE     VARCHAR(20),
    IS_ACTIVE         BOOLEAN DEFAULT true,
    CONSTRAINT pk_dispatch_points PRIMARY KEY (DISPATCH_POINT_ID),
    CONSTRAINT fk_dispatch_territory FOREIGN KEY (TERRITORY_ID) REFERENCES ASOP_TERRITORIES (TERRITORY_ID)
);
COMMENT
ON TABLE ASOP_DISPATCH_POINTS IS 'Физические пункты диспетчерского управления.';
CREATE INDEX idx_dispatch_geo ON ASOP_DISPATCH_POINTS USING GIST (GEO_LOCATION);

-- НОВОЕ: Справочник договоров/контрактов
CREATE TABLE ASOP_CONTRACTS
(
    CONTRACT_ID     UUID         NOT NULL,
    CONTRACT_NUMBER VARCHAR(100) NOT NULL,
    ORGANIZER_ID    UUID         NOT NULL,
    CARRIER_ID      UUID         NOT NULL,
    CONTRACT_DATE   DATE,
    VALID_FROM      DATE,
    VALID_UNTIL     DATE,
    DESCRIPTION     TEXT,
    CREATED_AT      TIMESTAMP    NOT NULL,
    UPDATED_AT      TIMESTAMP    NOT NULL,
    CONSTRAINT pk_contracts PRIMARY KEY (CONTRACT_ID),
    CONSTRAINT fk_contract_organizer FOREIGN KEY (ORGANIZER_ID) REFERENCES ASOP_ORGANIZERS (ORGANIZER_ID),
    CONSTRAINT fk_contract_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID)
);
COMMENT
ON TABLE ASOP_CONTRACTS IS 'Договоры с перевозчиками.';
CREATE INDEX idx_contracts_organizer ON ASOP_CONTRACTS (ORGANIZER_ID);
CREATE INDEX idx_contracts_carrier ON ASOP_CONTRACTS (CARRIER_ID);

-- НОВОЕ: Справочник платежных операторов
CREATE TABLE ASOP_PAYMENT_OPERATORS
(
    OPERATOR_ID       UUID         NOT NULL,
    OPERATOR_NAME     VARCHAR(255) NOT NULL,
    DESCRIPTION       TEXT,
    SEND_URI          VARCHAR(500),
    CHECK_URI         VARCHAR(500),
    RECEIPT_CHECK_URI VARCHAR(500),
    COUNTERPARTY_NAME VARCHAR(255),
    IS_ACTIVE         BOOLEAN DEFAULT true,
    CREATED_AT        TIMESTAMP    NOT NULL,
    UPDATED_AT        TIMESTAMP    NOT NULL,
    CONSTRAINT pk_payment_operators PRIMARY KEY (OPERATOR_ID)
);
COMMENT
ON TABLE ASOP_PAYMENT_OPERATORS IS 'Платежные операторы и сервисы.';

-- НОВОЕ: Корпоративные клиенты
CREATE TABLE ASOP_CORPORATE_CLIENTS
(
    CORPORATE_CLIENT_ID UUID         NOT NULL,
    CLIENT_NAME         VARCHAR(255) NOT NULL,
    CARD_ID             UUID,
    CARRIER_ID          UUID,
    CREATED_AT          TIMESTAMP    NOT NULL,
    UPDATED_AT          TIMESTAMP    NOT NULL,
    CONSTRAINT pk_corporate_clients PRIMARY KEY (CORPORATE_CLIENT_ID),
    CONSTRAINT fk_corp_client_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID),
    CONSTRAINT fk_corp_client_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID)
);
COMMENT
ON TABLE ASOP_CORPORATE_CLIENTS IS 'Корпоративные клиенты.';

-- ========================
-- 2. БАЗОВЫЕ СУЩНОСТИ
-- ========================

CREATE TABLE ASOP_CARRIERS
(
    CARRIER_ID   UUID         NOT NULL,
    CARRIER_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_carriers PRIMARY KEY (CARRIER_ID)
);

CREATE TABLE ASOP_USERS
(
    USER_ID       UUID NOT NULL,
    ROLE_ID       UUID NOT NULL,
    CARRIER_ID    UUID,
    SNILS         VARCHAR(14),
    PHONE         VARCHAR(20),
    USER_FIO      VARCHAR(255),
    PASSWORD_HASH VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (USER_ID),
    CONSTRAINT fk_users_role_id FOREIGN KEY (ROLE_ID) REFERENCES ASOP_ROLES (ROLE_ID),
    CONSTRAINT fk_users_carrier_id FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT uq_users_snils UNIQUE (SNILS)
);

CREATE TABLE ASOP_VEHICLES
(
    VEHICLE_ID     UUID         NOT NULL,
    CARRIER_ID     UUID         NOT NULL,
    VEHICLE_NUMBER VARCHAR(16)  NOT NULL,
    VEHICLE_NAME   VARCHAR(255) NOT NULL,
    VEHICLE_MODEL  VARCHAR(100),
    CONSTRAINT pk_vehicles PRIMARY KEY (VEHICLE_ID),
    CONSTRAINT fk_vehicles_carrier_id FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID)
);
COMMENT
ON COLUMN ASOP_VEHICLES.VEHICLE_MODEL IS 'Модель ТС.';

CREATE TABLE ASOP_TERMINALS
(
    TERMINAL_ID           UUID        NOT NULL,
    VEHICLE_ID            UUID,
    CARRIER_ID            UUID,
    TERMINAL_NUMBER       VARCHAR(16) NOT NULL,
    TERMINAL_SERIAL       VARCHAR(64) NOT NULL,
    DISPATCH_POINT_ID     UUID,
    BENEFITS_SYNC_TOKEN   VARCHAR(64),
    LAST_BENEFITS_SYNC_AT TIMESTAMP,
    CONSTRAINT pk_terminals PRIMARY KEY (TERMINAL_ID),
    CONSTRAINT fk_terminals_carrier_id FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_terminals_vehicle_id FOREIGN KEY (VEHICLE_ID) REFERENCES ASOP_VEHICLES (VEHICLE_ID),
    CONSTRAINT fk_terminals_dispatch FOREIGN KEY (DISPATCH_POINT_ID) REFERENCES ASOP_DISPATCH_POINTS (DISPATCH_POINT_ID)
);

CREATE TABLE ASOP_TIDS
(
    TID_ID        UUID        NOT NULL,
    CARRIER_ID    UUID        NOT NULL,
    TERMINAL_ID   UUID,
    TID_VALUE     VARCHAR(20) NOT NULL,
    STATUS        VARCHAR(20) DEFAULT 'UNUSED',
    ASSIGNED_AT   TIMESTAMP,
    UNASSIGNED_AT TIMESTAMP,
    CREATED_AT    TIMESTAMP   NOT NULL,
    UPDATED_AT    TIMESTAMP   NOT NULL,
    CONSTRAINT pk_tids PRIMARY KEY (TID_ID),
    CONSTRAINT fk_tids_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_tids_terminal FOREIGN KEY (TERMINAL_ID) REFERENCES ASOP_TERMINALS (TERMINAL_ID),
    CONSTRAINT uq_tids_value UNIQUE (TID_VALUE),
    CONSTRAINT uq_tids_terminal UNIQUE (TERMINAL_ID),
    CONSTRAINT chk_tid_status CHECK (STATUS IN ('UNUSED', 'ASSIGNED', 'REVOKED'))
);
CREATE INDEX idx_tids_carrier ON ASOP_TIDS (CARRIER_ID);
CREATE INDEX idx_tids_terminal ON ASOP_TIDS (TERMINAL_ID);

-- ========================
-- 3. МАРШРУТЫ И РАСПИСАНИЕ
-- ========================

CREATE TABLE ASOP_ROUTES
(
    ROUTE_ID             UUID         NOT NULL,
    ROUTE_TYPE_ID        UUID         NOT NULL,
    PARENT_ROUTE_ID      UUID,
    ROUTE_NAME           VARCHAR(128) NOT NULL,
    MINISTRY_REGISTRY_NO VARCHAR(50),
    ROUTE_CATEGORY       VARCHAR(30) CHECK (ROUTE_CATEGORY IN ('CITY', 'SUBURBAN', 'INTERCITY', 'EXPRESS')),
    TERRITORY_ID         UUID,
    ORGANIZER_ID         UUID,
    ROUTE_START_DATE     TIMESTAMP,
    ROUTE_END_DATE       TIMESTAMP,
    BENEFIT_POLICY       VARCHAR(20)  NOT NULL DEFAULT 'ALL' CHECK (BENEFIT_POLICY IN ('ALL', 'ALLOWLIST', 'NONE')),
    ROUTE_OBJECT         JSONB,
    DESCRIPTION          VARCHAR(512),
    CREATED_AT           TIMESTAMP    NOT NULL,
    UPDATED_AT           TIMESTAMP    NOT NULL,
    CONSTRAINT pk_routes PRIMARY KEY (ROUTE_ID),
    CONSTRAINT fk_routes_type_id FOREIGN KEY (ROUTE_TYPE_ID) REFERENCES ASOP_ROUTE_TYPES (ROUTE_TYPE_ID),
    CONSTRAINT fk_routes_parent_id FOREIGN KEY (PARENT_ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID),
    CONSTRAINT fk_routes_territory FOREIGN KEY (TERRITORY_ID) REFERENCES ASOP_TERRITORIES (TERRITORY_ID),
    CONSTRAINT fk_routes_organizer FOREIGN KEY (ORGANIZER_ID) REFERENCES ASOP_ORGANIZERS (ORGANIZER_ID),
    CONSTRAINT chk_routes_valid_dates CHECK (ROUTE_START_DATE IS NULL OR ROUTE_END_DATE IS NULL OR
                                             ROUTE_END_DATE > ROUTE_START_DATE)
);
CREATE INDEX idx_routes_validity ON ASOP_ROUTES (ROUTE_START_DATE, ROUTE_END_DATE);
CREATE INDEX idx_routes_policy ON ASOP_ROUTES (BENEFIT_POLICY);
CREATE INDEX idx_routes_category ON ASOP_ROUTES (ROUTE_CATEGORY);

CREATE TABLE ASOP_TRANSPORT_STOPS
(
    STOP_ID      UUID         NOT NULL,
    FARE_ZONE_ID UUID,
    STOP_CODE    VARCHAR(20)  NOT NULL,
    STOP_NAME    VARCHAR(200) NOT NULL,
    STOP_ADDRESS VARCHAR(500),
    ZONE_POLYGON GEOGRAPHY(POLYGON, 4326),
    DESCRIPTION  TEXT,
    IS_ACTIVE    BOOLEAN DEFAULT true,
    CREATED_AT   TIMESTAMP    NOT NULL,
    UPDATED_AT   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_transport_stops PRIMARY KEY (STOP_ID),
    CONSTRAINT uq_stop_code UNIQUE (STOP_CODE),
    CONSTRAINT fk_transport_stops_zone_id FOREIGN KEY (FARE_ZONE_ID) REFERENCES ASOP_FARE_ZONES (ZONE_ID)
);
CREATE INDEX idx_transport_stops_geo ON ASOP_TRANSPORT_STOPS USING GIST (ZONE_POLYGON);

CREATE TABLE ASOP_ROUTE_TRANSPORT_STOPS
(
    ROUTE_STOP_ID UUID      NOT NULL,
    STOP_ID       UUID      NOT NULL,
    ROUTE_ID      UUID      NOT NULL,
    SERIAL_NUMBER INT       NOT NULL,
    CREATED_AT    TIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP NOT NULL,
    CONSTRAINT pk_route_transport_stops PRIMARY KEY (ROUTE_STOP_ID),
    CONSTRAINT fk_route_transport_stops_stop_id FOREIGN KEY (STOP_ID) REFERENCES ASOP_TRANSPORT_STOPS (STOP_ID),
    CONSTRAINT fk_route_transport_stops_route_id FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID)
);
CREATE UNIQUE INDEX uk_route_transport_stops ON ASOP_ROUTE_TRANSPORT_STOPS (ROUTE_ID, STOP_ID);

CREATE TABLE ASOP_SCHEDULE
(
    SCHEDULE_ID    UUID NOT NULL,
    ROUTE_ID       UUID NOT NULL,
    STOP_ID        UUID NOT NULL,
    DAY_MASK       INT  NOT NULL DEFAULT 127,
    ARRIVAL_TIME   TIME NOT NULL,
    DWELL_TIME_SEC INT           DEFAULT 30,
    IS_ACTIVE      BOOLEAN       DEFAULT true,
    CONSTRAINT pk_schedule PRIMARY KEY (SCHEDULE_ID),
    CONSTRAINT fk_sched_route FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_sched_stop FOREIGN KEY (STOP_ID) REFERENCES ASOP_TRANSPORT_STOPS (STOP_ID),
    CONSTRAINT chk_day_mask CHECK (DAY_MASK BETWEEN 1 AND 127)
);
CREATE INDEX idx_sched_route_stop ON ASOP_SCHEDULE (ROUTE_ID, STOP_ID);
CREATE INDEX idx_sched_time ON ASOP_SCHEDULE (ARRIVAL_TIME);

CREATE TABLE ASOP_ROUTE_SERVICES
(
    ROUTE_SERVICE_ID UUID NOT NULL,
    ROUTE_ID         UUID NOT NULL,
    SERVICE_ID       UUID NOT NULL,
    CONSTRAINT pk_route_services PRIMARY KEY (ROUTE_SERVICE_ID),
    CONSTRAINT fk_rs_route FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_rs_service FOREIGN KEY (SERVICE_ID) REFERENCES ASOP_SERVICES (SERVICE_ID),
    CONSTRAINT uq_route_service UNIQUE (ROUTE_ID, SERVICE_ID)
);

CREATE TABLE ASOP_ROUTE_CARD_TYPES
(
    ROUTE_CARD_TYPE_ID UUID NOT NULL,
    ROUTE_ID           UUID NOT NULL,
    CARD_TYPE_ID       UUID NOT NULL,
    IS_ENABLED         BOOLEAN DEFAULT true,
    CONSTRAINT pk_route_card_types PRIMARY KEY (ROUTE_CARD_TYPE_ID),
    CONSTRAINT fk_rct_route FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_rct_type FOREIGN KEY (CARD_TYPE_ID) REFERENCES ASOP_CARD_TYPES (CARD_TYPE_ID),
    CONSTRAINT uq_route_card_type UNIQUE (ROUTE_ID, CARD_TYPE_ID)
);

CREATE TABLE ASOP_ROUTE_DISCOUNTS
(
    ROUTE_DISCOUNT_ID UUID          NOT NULL,
    ROUTE_ID          UUID          NOT NULL,
    DISCOUNT_NAME     VARCHAR(100)  NOT NULL,
    DISCOUNT_PERCENT  NUMERIC(5, 2) NOT NULL CHECK (DISCOUNT_PERCENT BETWEEN 0 AND 100),
    VALID_FROM        TIMESTAMP     NOT NULL,
    VALID_UNTIL       TIMESTAMP,
    IS_ACTIVE         BOOLEAN DEFAULT true,
    CONSTRAINT pk_route_discounts PRIMARY KEY (ROUTE_DISCOUNT_ID),
    CONSTRAINT fk_rd_route FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID) ON DELETE CASCADE,
    CONSTRAINT chk_rd_validity CHECK (VALID_UNTIL IS NULL OR VALID_UNTIL > VALID_FROM)
);
CREATE INDEX idx_rd_route_active ON ASOP_ROUTE_DISCOUNTS (ROUTE_ID, IS_ACTIVE) WHERE IS_ACTIVE = true;

-- ========================
-- 4. КАРТЫ, ЛЬГОТЫ, ТАРИФЫ
-- ========================

CREATE TABLE ASOP_CARDS
(
    CARD_ID               UUID      NOT NULL,
    CARD_TYPE_ID          UUID      NOT NULL,
    USER_ID               UUID,
    REGISTERED_AT         TIMESTAMP,
    REGISTERED_BY_USER_ID UUID,
    CREATED_AT            TIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP NOT NULL,
    CONSTRAINT pk_cards PRIMARY KEY (CARD_ID),
    CONSTRAINT fk_cards_type_id FOREIGN KEY (CARD_TYPE_ID) REFERENCES ASOP_CARD_TYPES (CARD_TYPE_ID),
    CONSTRAINT fk_cards_user_id FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID)
);

CREATE TABLE ASOP_CARD_MIFARES
(
    CARD_ID          UUID  NOT NULL,
    UID              BYTEA NOT NULL,
    ATQA             SMALLINT,
    SAK              SMALLINT,
    PROTOCOL_VERSION INT,
    MEMORY_MAP       JSONB,
    CONSTRAINT pk_card_mifares PRIMARY KEY (CARD_ID),
    CONSTRAINT uq_mifare_uid UNIQUE (UID),
    CONSTRAINT fk_mifares_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID) ON DELETE CASCADE
);

CREATE TABLE ASOP_CARD_BANKS
(
    CARD_ID      UUID         NOT NULL,
    PAN_TOKEN    VARCHAR(256) NOT NULL,
    PAN_LAST4    CHAR(4),
    BIN          CHAR(6),
    IS_TOKENIZED BOOLEAN DEFAULT false,
    CONSTRAINT pk_card_banks PRIMARY KEY (CARD_ID),
    CONSTRAINT fk_banks_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID) ON DELETE CASCADE
);

CREATE TABLE ASOP_CARD_TARIFFS
(
    CARD_TARIFF_ID          UUID      NOT NULL,
    CARD_ID                 UUID      NOT NULL,
    TARIFF_TYPE_ID          UUID      NOT NULL,
    BALANCE                 NUMERIC(10, 2),
    TRAVEL_COUNT            INT,
    MAX_TRAVEL_COUNT        INT,
    EXPIRATION_DATE         TIMESTAMP,
    ACTIVATED_AT            TIMESTAMP,
    PURCHASE_TRANSACTION_ID UUID,
    IS_ACTIVE               BOOLEAN DEFAULT true,
    CREATED_AT              TIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP NOT NULL,
    CONSTRAINT pk_card_tariffs PRIMARY KEY (CARD_TARIFF_ID),
    CONSTRAINT fk_card_tariffs_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID) ON DELETE CASCADE,
    CONSTRAINT fk_card_tariffs_type FOREIGN KEY (TARIFF_TYPE_ID) REFERENCES ASOP_TARIFF_TYPES (TARIFF_TYPE_ID)
);

CREATE TABLE ASOP_BLACKLISTS
(
    CARD_ID    UUID        NOT NULL,
    BLOCK_TYPE VARCHAR(20) NOT NULL,
    BLOCKED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_blacklists PRIMARY KEY (CARD_ID),
    CONSTRAINT fk_blacklists_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID),
    CONSTRAINT chk_blacklist_type CHECK (BLOCK_TYPE IN ('PERMANENT', 'NEGATIVE_BALANCE'))
);

CREATE TABLE ASOP_BENEFITS
(
    BENEFIT_ID   UUID         NOT NULL,
    BENEFIT_CODE VARCHAR(50)  NOT NULL,
    BENEFIT_NAME VARCHAR(100) NOT NULL,
    REGION_CODE  VARCHAR(50)  NOT NULL,
    DESCRIPTION  TEXT,
    IS_ACTIVE    BOOLEAN DEFAULT true,
    CREATED_AT   TIMESTAMP    NOT NULL,
    UPDATED_AT   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_benefits PRIMARY KEY (BENEFIT_ID),
    CONSTRAINT uq_benefits_code UNIQUE (BENEFIT_CODE)
);

CREATE TABLE ASOP_BENEFIT_STEPS
(
    STEP_ID             UUID          NOT NULL,
    BENEFIT_ID          UUID          NOT NULL,
    STEP_ORDER          INT           NOT NULL,
    TRIP_THRESHOLD_FROM INT           NOT NULL DEFAULT 0,
    TRIP_THRESHOLD_TO   INT,
    DISCOUNT_SHARE      NUMERIC(4, 2) NOT NULL CHECK (DISCOUNT_SHARE BETWEEN 0 AND 1),
    PERIOD_TYPE         VARCHAR(20)   NOT NULL DEFAULT 'MONTHLY',
    CONSTRAINT pk_benefit_steps PRIMARY KEY (STEP_ID),
    CONSTRAINT fk_steps_benefit FOREIGN KEY (BENEFIT_ID) REFERENCES ASOP_BENEFITS (BENEFIT_ID) ON DELETE CASCADE,
    CONSTRAINT uq_benefit_steps_order UNIQUE (BENEFIT_ID, STEP_ORDER),
    CONSTRAINT chk_steps_range CHECK (TRIP_THRESHOLD_TO IS NULL OR TRIP_THRESHOLD_TO > TRIP_THRESHOLD_FROM)
);

CREATE TABLE ASOP_USER_BENEFITS
(
    ASSIGNMENT_ID UUID      NOT NULL,
    USER_ID       UUID      NOT NULL,
    BENEFIT_ID    UUID      NOT NULL,
    VALID_FROM    TIMESTAMP NOT NULL,
    VALID_UNTIL   TIMESTAMP,
    SYNC_VERSION  INT       NOT NULL DEFAULT 1,
    CREATED_AT    TIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP NOT NULL,
    CONSTRAINT pk_user_benefits PRIMARY KEY (ASSIGNMENT_ID),
    CONSTRAINT fk_ub_user FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT fk_ub_benefit FOREIGN KEY (BENEFIT_ID) REFERENCES ASOP_BENEFITS (BENEFIT_ID)
);

CREATE TABLE ASOP_ROUTE_BENEFITS
(
    ROUTE_BENEFIT_ID UUID NOT NULL,
    ROUTE_ID         UUID NOT NULL,
    BENEFIT_ID       UUID NOT NULL,
    CONSTRAINT pk_route_benefits PRIMARY KEY (ROUTE_BENEFIT_ID),
    CONSTRAINT fk_rb_route FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_rb_benefit FOREIGN KEY (BENEFIT_ID) REFERENCES ASOP_BENEFITS (BENEFIT_ID) ON DELETE CASCADE,
    CONSTRAINT uq_route_benefit UNIQUE (ROUTE_ID, BENEFIT_ID)
);

CREATE TABLE ASOP_TARIFF_RATES
(
    TARIFF_RATE_ID UUID           NOT NULL,
    TARIFF_TYPE_ID UUID           NOT NULL,
    CARRIER_ID     UUID,
    ZONE_ID        UUID,
    ROUTE_ID       UUID,
    PRICE          NUMERIC(10, 2) NOT NULL,
    DESCRIPTION    TEXT,
    IS_ACTIVE      BOOLEAN DEFAULT true,
    CREATED_AT     TIMESTAMP      NOT NULL,
    UPDATED_AT     TIMESTAMP      NOT NULL,
    CONSTRAINT pk_tariff_rates PRIMARY KEY (TARIFF_RATE_ID),
    CONSTRAINT fk_tariff_rates_type FOREIGN KEY (TARIFF_TYPE_ID) REFERENCES ASOP_TARIFF_TYPES (TARIFF_TYPE_ID),
    CONSTRAINT fk_tariff_rates_carrier FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_tariff_rates_zone FOREIGN KEY (ZONE_ID) REFERENCES ASOP_FARE_ZONES (ZONE_ID),
    CONSTRAINT fk_tariff_rates_route FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID)
);

CREATE TABLE ASOP_CARRIER_ZONES
(
    CARRIER_ZONE_ID UUID           NOT NULL,
    CARRIER_ID      UUID           NOT NULL,
    ZONE_ID         UUID           NOT NULL,
    BASE_FARE       DECIMAL(10, 2) NOT NULL,
    CREATED_AT      TIMESTAMP      NOT NULL,
    UPDATED_AT      TIMESTAMP      NOT NULL,
    CONSTRAINT pk_carrier_zones PRIMARY KEY (CARRIER_ZONE_ID),
    CONSTRAINT fk_carrier_zones_carrier_id FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_carrier_zones_zone_id FOREIGN KEY (ZONE_ID) REFERENCES ASOP_FARE_ZONES (ZONE_ID)
);
CREATE INDEX idx_tariff_rates_active ON ASOP_TARIFF_RATES (IS_ACTIVE) WHERE IS_ACTIVE = true;
CREATE UNIQUE INDEX uk_carrier_zones ON ASOP_CARRIER_ZONES (CARRIER_ID, ZONE_ID);

-- ========================
-- 5. СЕССИИ, ТРАНЗАКЦИИ, РЕЙСЫ, ДИСПЕТЧЕРИЗАЦИЯ
-- ========================

CREATE TABLE ASOP_USER_SESSIONS
(
    SESSION_ID        UUID      NOT NULL,
    TERMINAL_ID       UUID      NOT NULL,
    OPENED_BY_USER_ID UUID,
    CLOSED_BY_USER_ID UUID,
    CARD_ID           UUID,
    STARTED_AT        TIMESTAMP NOT NULL,
    CLOSED_AT         TIMESTAMP,
    STARTED_AT_LOCAL  TIMESTAMP NOT NULL,
    CLOSED_AT_LOCAL   TIMESTAMP,
    EXPIRATION_TIME   TIMESTAMP NOT NULL,
    CONSTRAINT pk_user_sessions PRIMARY KEY (SESSION_ID),
    CONSTRAINT fk_sessions_terminal_id FOREIGN KEY (TERMINAL_ID) REFERENCES ASOP_TERMINALS (TERMINAL_ID),
    CONSTRAINT fk_sessions_opened_by FOREIGN KEY (OPENED_BY_USER_ID) REFERENCES ASOP_USERS (USER_ID) ON DELETE SET NULL,
    CONSTRAINT fk_sessions_closed_by FOREIGN KEY (CLOSED_BY_USER_ID) REFERENCES ASOP_USERS (USER_ID) ON DELETE SET NULL,
    CONSTRAINT fk_sessions_card_id FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID)
);

CREATE TABLE ASOP_TRIPS
(
    TRIP_ID              UUID      NOT NULL,
    ROUTE_ID             UUID      NOT NULL,
    SESSION_ID           UUID      NOT NULL,
    STARTED_AT           TIMESTAMP NOT NULL,
    CLOSED_AT            TIMESTAMP,
    STARTED_AT_LOCAL     TIMESTAMP NOT NULL,
    CLOSED_AT_LOCAL      TIMESTAMP,
    TRIP_STATUS          VARCHAR(20) DEFAULT 'IN_PROGRESS',
    CONFIRMED_BY_USER_ID UUID,
    CONSTRAINT pk_trips PRIMARY KEY (TRIP_ID),
    CONSTRAINT fk_trips_route_id FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID),
    CONSTRAINT fk_trips_session_id FOREIGN KEY (SESSION_ID) REFERENCES ASOP_USER_SESSIONS (SESSION_ID),
    CONSTRAINT fk_trips_confirmed_by FOREIGN KEY (CONFIRMED_BY_USER_ID) REFERENCES ASOP_USERS (USER_ID) ON DELETE SET NULL,
    CONSTRAINT chk_trip_status CHECK (TRIP_STATUS IN ('IN_PROGRESS', 'CONFIRMED', 'UNCONFIRMED', 'CANCELLED'))
);
CREATE INDEX idx_trips_route_id ON ASOP_TRIPS (ROUTE_ID);
CREATE INDEX idx_trips_status_route ON ASOP_TRIPS (ROUTE_ID, TRIP_STATUS);

CREATE TABLE ASOP_TRANSACTIONS
(
    TRANSACTION_ID        UUID           NOT NULL,
    STARTED_AT            TIMESTAMP      NOT NULL,
    COMPLETED_AT          TIMESTAMP,
    TERMINAL_ID           UUID           NOT NULL,
    SESSION_ID            UUID,
    TRIP_ID               UUID,
    TRANSACTION_TYPE_ID   UUID           NOT NULL,
    TRANSACTION_RESULT_ID UUID           NOT NULL,
    AMOUNT                NUMERIC(10, 2) NOT NULL DEFAULT 0,
    CURRENCY              CHAR(3)                 DEFAULT 'RUB',
    ACQUIRER_REFERENCE    VARCHAR(128),
    ERROR_CODE            VARCHAR(50),
    ERROR_MESSAGE         VARCHAR(512),
    METADATA              JSONB,
    CONSTRAINT pk_transactions PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT fk_transactions_terminal FOREIGN KEY (TERMINAL_ID) REFERENCES ASOP_TERMINALS (TERMINAL_ID),
    CONSTRAINT fk_transactions_session FOREIGN KEY (SESSION_ID) REFERENCES ASOP_USER_SESSIONS (SESSION_ID),
    CONSTRAINT fk_transactions_trip FOREIGN KEY (TRIP_ID) REFERENCES ASOP_TRIPS (TRIP_ID),
    CONSTRAINT fk_transactions_type FOREIGN KEY (TRANSACTION_TYPE_ID) REFERENCES ASOP_TRANSACTION_TYPES (TRANSACTION_TYPE_ID),
    CONSTRAINT fk_transactions_result FOREIGN KEY (TRANSACTION_RESULT_ID) REFERENCES ASOP_TRANSACTION_RESULTS (TRANSACTION_RESULT_ID)
);

CREATE TABLE ASOP_TRANSACTION_CARDS
(
    TRANSACTION_CARD_ID UUID        NOT NULL,
    TRANSACTION_ID      UUID        NOT NULL,
    CARD_ID             UUID        NOT NULL,
    CARD_ROLE           VARCHAR(20) NOT NULL,
    TARIFF_APPLIED_ID   UUID,
    BALANCE_BEFORE      NUMERIC(10, 2),
    BALANCE_AFTER       NUMERIC(10, 2),
    CONSTRAINT pk_transaction_cards PRIMARY KEY (TRANSACTION_CARD_ID),
    CONSTRAINT fk_tc_transaction FOREIGN KEY (TRANSACTION_ID) REFERENCES ASOP_TRANSACTIONS (TRANSACTION_ID) ON DELETE CASCADE,
    CONSTRAINT fk_tc_card FOREIGN KEY (CARD_ID) REFERENCES ASOP_CARDS (CARD_ID),
    CONSTRAINT fk_tc_tariff FOREIGN KEY (TARIFF_APPLIED_ID) REFERENCES ASOP_CARD_TARIFFS (CARD_TARIFF_ID)
);
ALTER TABLE ASOP_CARD_TARIFFS
    ADD CONSTRAINT fk_tariff_purchase FOREIGN KEY (PURCHASE_TRANSACTION_ID) REFERENCES ASOP_TRANSACTIONS (TRANSACTION_ID);

CREATE TABLE ASOP_DISPATCH_POSITIONS
(
    POSITION_ID       UUID      NOT NULL,
    VEHICLE_ID        UUID      NOT NULL,
    ROUTE_ID          UUID      NOT NULL,
    TRIP_ID           UUID,
    GPS_COORD         GEOGRAPHY(POINT, 4326),
    RECORDED_AT       TIMESTAMP NOT NULL,
    SPEED_KMH         NUMERIC(5, 2),
    STATUS            VARCHAR(30) DEFAULT 'MOVING',
    DISPATCH_POINT_ID UUID,
    CONSTRAINT pk_dispatch_positions PRIMARY KEY (POSITION_ID),
    CONSTRAINT fk_dp_vehicle FOREIGN KEY (VEHICLE_ID) REFERENCES ASOP_VEHICLES (VEHICLE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_dp_route FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID),
    CONSTRAINT fk_dp_trip FOREIGN KEY (TRIP_ID) REFERENCES ASOP_TRIPS (TRIP_ID),
    CONSTRAINT fk_dp_point FOREIGN KEY (DISPATCH_POINT_ID) REFERENCES ASOP_DISPATCH_POINTS (DISPATCH_POINT_ID)
);
CREATE INDEX idx_dp_vehicle_time ON ASOP_DISPATCH_POSITIONS (VEHICLE_ID, RECORDED_AT DESC);
CREATE INDEX idx_dp_route_time ON ASOP_DISPATCH_POSITIONS (ROUTE_ID, RECORDED_AT DESC);
CREATE INDEX idx_dp_geo ON ASOP_DISPATCH_POSITIONS USING GIST (GPS_COORD);

CREATE TABLE ASOP_CARRIER_ROUTES
(
    CARRIER_ROUTE_ID UUID      NOT NULL,
    CARRIER_ID       UUID      NOT NULL,
    ROUTE_ID         UUID      NOT NULL,
    CREATED_AT       TIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP NOT NULL,
    CONSTRAINT pk_carrier_routes PRIMARY KEY (CARRIER_ROUTE_ID),
    CONSTRAINT fk_carrier_routes_carrier_id FOREIGN KEY (CARRIER_ID) REFERENCES ASOP_CARRIERS (CARRIER_ID),
    CONSTRAINT fk_carrier_routes_route_id FOREIGN KEY (ROUTE_ID) REFERENCES ASOP_ROUTES (ROUTE_ID)
);
CREATE UNIQUE INDEX uk_carrier_routes ON ASOP_CARRIER_ROUTES (CARRIER_ID, ROUTE_ID);

CREATE TABLE ASOP_EVENTS
(
    EVENT_ID          UUID      NOT NULL,
    EVENT_TIME        TIMESTAMP NOT NULL,
    EVENT_LOCAL_TIME  TIMESTAMP NOT NULL,
    EVENT_TYPE        CHAR(4)   NOT NULL,
    USER_ID           UUID,
    SESSION_ID        UUID,
    REFERENCE_TYPE_ID INT,
    REFERENCE_ID      UUID,
    EVENT_DETAILS     VARCHAR(256),
    EVENT_OBJECT      JSONB,
    CONSTRAINT pk_events PRIMARY KEY (EVENT_ID),
    CONSTRAINT fk_events_type FOREIGN KEY (EVENT_TYPE) REFERENCES ASOP_EVENT_TYPES (EVENT_TYPE),
    CONSTRAINT fk_events_session_id FOREIGN KEY (SESSION_ID) REFERENCES ASOP_USER_SESSIONS (SESSION_ID),
    CONSTRAINT fk_events_user_id FOREIGN KEY (USER_ID) REFERENCES ASOP_USERS (USER_ID)
);
CREATE INDEX idx_events_time ON ASOP_EVENTS (EVENT_TIME, USER_ID);

-- ========================
-- 6. ИНДЕКСЫ И ДОКУМЕНТАЦИЯ
-- ========================
CREATE INDEX idx_users_snils ON ASOP_USERS (SNILS) WHERE SNILS IS NOT NULL;
CREATE INDEX idx_blacklists_type ON ASOP_BLACKLISTS (BLOCK_TYPE);
CREATE INDEX idx_card_tariffs_expiry ON ASOP_CARD_TARIFFS (EXPIRATION_DATE) WHERE IS_ACTIVE = true;
CREATE INDEX idx_transactions_completed_at ON ASOP_TRANSACTIONS (COMPLETED_AT) WHERE COMPLETED_AT IS NULL;
CREATE UNIQUE INDEX uk_transaction_cards_main ON ASOP_TRANSACTION_CARDS (TRANSACTION_ID, CARD_ID);
CREATE INDEX idx_rb_route ON ASOP_ROUTE_BENEFITS (ROUTE_ID);
CREATE INDEX idx_ub_user ON ASOP_USER_BENEFITS (USER_ID);
CREATE INDEX idx_sched_route ON ASOP_SCHEDULE (ROUTE_ID, ARRIVAL_TIME);
CREATE INDEX idx_travel_zones_fare ON ASOP_TRAVEL_ZONES (FARE_ZONE_ID);

COMMENT
ON TABLE ASOP_EVENTS IS 'Журнал системных действий.';
COMMENT
ON TABLE ASOP_TRANSACTIONS IS 'Финансовые проводки.';
COMMENT
ON TABLE ASOP_DISPATCH_POSITIONS IS 'Трекинг ТС.';
COMMENT
ON TABLE ASOP_SCHEDULE IS 'Расписание.';
COMMENT
ON TABLE ASOP_TERRITORIES IS 'Территории.';
COMMENT
ON TABLE ASOP_SERVICES IS 'Платные услуги.';
COMMENT
ON TABLE ASOP_TIDS IS 'Пул TID.';
COMMENT
ON TABLE ASOP_TRIPS IS 'Рейсы. TRIP_STATUS управляет статусом отработки маршрута.';
COMMENT
ON TABLE ASOP_CONTRACTS IS 'Договоры с перевозчиками.';
COMMENT
ON TABLE ASOP_PAYMENT_OPERATORS IS 'Платежные операторы.';
COMMENT
ON TABLE ASOP_CORPORATE_CLIENTS IS 'Корпоративные клиенты.';