-- ============================================================
-- СКРИПТ СОЗДАНИЯ БАЗЫ ДАННЫХ TAVRIDA (PostgreSQL)
-- Сгенерировано на основе Liquibase changelog.xml
-- ============================================================

-- 1. Справочник ролей пользователей
CREATE TABLE USER_ROLES (
    USER_ROLE_ID INT NOT NULL,
    USER_ROLE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (USER_ROLE_ID)
);

INSERT INTO USER_ROLES (USER_ROLE_ID, USER_ROLE_NAME) VALUES
(1, 'Администратор'),
(2, 'Администратор перевозчика'),
(3, 'Кассир'),
(4, 'Водитель');

-- 2. Справочник типов карт
CREATE TABLE CARD_TYPES (
    CARD_TYPE_ID INT NOT NULL,
    CARD_TYPE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_card_types PRIMARY KEY (CARD_TYPE_ID)
);

INSERT INTO CARD_TYPES (CARD_TYPE_ID, CARD_TYPE_NAME) VALUES
(1, 'Карта администратора'),
(2, 'Карта кассира'),
(3, 'Карта водителя'),
(4, 'Карта пассажира'),
(5, 'Карта активации терминала'),
(6, 'Карта сброса терминала');

-- 3. Перевозчики
CREATE TABLE CARRIERS (
    CARRIER_ID BIGSERIAL NOT NULL,
    CARRIER_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_carriers PRIMARY KEY (CARRIER_ID)
);

ALTER SEQUENCE CARRIERS_CARRIER_ID_SEQ RESTART WITH 1000;

-- 4. Пользователи
CREATE TABLE USERS (
    USER_ID BIGSERIAL NOT NULL,
    USER_ROLE_ID INT NOT NULL,
    USER_FIO VARCHAR(255),
    CARRIER_ID BIGINT,
    USER_PASSWORD_HASH VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (USER_ID),
    CONSTRAINT fk_users_user_role_id FOREIGN KEY (USER_ROLE_ID)
        REFERENCES USER_ROLES(USER_ROLE_ID),
    CONSTRAINT fk_users_carrier_id FOREIGN KEY (CARRIER_ID)
        REFERENCES CARRIERS(CARRIER_ID)
);

ALTER SEQUENCE USERS_USER_ID_SEQ RESTART WITH 1000;

-- 5. Транспорт
CREATE TABLE TRANSPORTS (
    TRANSPORT_ID BIGSERIAL NOT NULL,
    TRANSPORT_GUID UUID NOT NULL,
    CARRIER_ID BIGINT NOT NULL,
    TRANSPORT_NUMBER VARCHAR(16) NOT NULL,
    TRANSPORT_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_transports PRIMARY KEY (TRANSPORT_ID),
    CONSTRAINT uq_transports_guid UNIQUE (TRANSPORT_GUID),
    CONSTRAINT fk_transports_carrier_id FOREIGN KEY (CARRIER_ID)
        REFERENCES CARRIERS(CARRIER_ID)
);

ALTER SEQUENCE TRANSPORTS_TRANSPORT_ID_SEQ RESTART WITH 1000;

-- 6. Терминалы
CREATE TABLE TERMINALS (
    TERMINAL_ID BIGSERIAL NOT NULL,
    TRANSPORT_ID BIGINT,
    CARRIER_ID BIGINT,
    TERMINAL_GUID UUID NOT NULL,
    TERMINAL_NUMBER VARCHAR(16) NOT NULL,
    TERMINAL_SERIAL VARCHAR(64) NOT NULL,
    CONSTRAINT pk_terminals PRIMARY KEY (TERMINAL_ID),
    CONSTRAINT uq_terminals_guid UNIQUE (TERMINAL_GUID),
    CONSTRAINT fk_terminals_carrier_id FOREIGN KEY (CARRIER_ID)
        REFERENCES CARRIERS(CARRIER_ID),
    CONSTRAINT fk_terminals_transport_id FOREIGN KEY (TRANSPORT_ID)
        REFERENCES TRANSPORTS(TRANSPORT_ID)
);

ALTER SEQUENCE TERMINALS_TERMINAL_ID_SEQ RESTART WITH 1000;

-- 7. Типы тарифов
CREATE TABLE TARIFF_TYPES (
    TARIFF_TYPE_ID INT NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    CONSTRAINT pk_tariff_types PRIMARY KEY (TARIFF_TYPE_ID),
    CONSTRAINT uq_tariff_types_code UNIQUE (CODE)
);

INSERT INTO TARIFF_TYPES (TARIFF_TYPE_ID, CODE, NAME, DESCRIPTION) VALUES
(1, 'RIDES_PACKAGE', 'Пакет поездок до даты',
 'Фиксированное количество поездок (например, 10 или 20), которые нужно использовать до определённой даты. Остаток поездок - в AVAILABLE_TRAVEL_COUNT, срок - в EXPIRATION_RIDES_PACKAGE карты.'),
(2, 'UNLIMITED_TILL_DATE', 'Безлимит до даты',
 'Безлимитное количество поездок в течение определённого периода (день/неделя/месяц/год). Срок действия указан в поле unlimited_until_date карты.'),
(3, 'WALLET', 'Пополняемый кошелёк',
 'Деньги списываются с баланса за каждую поездку. Баланс хранится в поле wallet_balance карты. Можно пополнять.');

-- 8. Карты
CREATE TABLE CARDS (
    CARD_ID BIGSERIAL NOT NULL,
    CARD_GUID UUID NOT NULL,
    CARD_TYPE_ID INT NOT NULL,
    USER_ID BIGINT,
    TRANSPORT_ID BIGINT,
    TARIFF_TYPE_ID INT,
    EXPIRATION_RIDES_PACKAGE TIMESTAMP NOT NULL,
    AVAILABLE_TRAVEL_COUNT INT NOT NULL,
    UNLIMITED_UNTIL_DATE TIMESTAMP,
    WALLET_BALANCE DECIMAL(10,2),
    UNIQUE_TRAVEL_COUNT INT NOT NULL,
    MAXIMUM_UNIQUE_COUNT INT NOT NULL,
    ISSUE_DATE TIMESTAMP NOT NULL,
    EXPIRATION_DATE TIMESTAMP NOT NULL,
    CONSTRAINT pk_cards PRIMARY KEY (CARD_ID),
    CONSTRAINT uq_cards_guid UNIQUE (CARD_GUID),
    CONSTRAINT fk_cards_card_type_id FOREIGN KEY (CARD_TYPE_ID)
        REFERENCES CARD_TYPES(CARD_TYPE_ID),
    CONSTRAINT fk_cards_user_id FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),
    CONSTRAINT fk_cards_transport_id FOREIGN KEY (TRANSPORT_ID)
        REFERENCES TRANSPORTS(TRANSPORT_ID),
    CONSTRAINT fk_cards_tariff_type_id FOREIGN KEY (TARIFF_TYPE_ID)
        REFERENCES TARIFF_TYPES(TARIFF_TYPE_ID)
);

ALTER SEQUENCE CARDS_CARD_ID_SEQ RESTART WITH 1000;

-- 9. CHECK-ограничение для таблицы CARDS
ALTER TABLE CARDS
ADD CONSTRAINT chk_cards_travel_count
CHECK (AVAILABLE_TRAVEL_COUNT >= 0);

-- 10. Чёрный список
CREATE TABLE BLACK_LIST (
    CARD_GUID UUID NOT NULL,
    CONSTRAINT pk_black_list PRIMARY KEY (CARD_GUID)
);

-- 11. Индексы
CREATE INDEX idx_cards_guid ON CARDS(CARD_GUID);
CREATE INDEX idx_blacklist_guid ON BLACK_LIST(CARD_GUID);
CREATE INDEX idx_terminals_guid ON TERMINALS(TERMINAL_GUID);

-- 12. Сессии пользователей
CREATE TABLE USER_SESSIONS (
    SESSION_ID UUID NOT NULL,
    TERMINAL_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CARD_ID BIGINT,
    STARTED_AT TIMESTAMP NOT NULL,
    CLOSED_AT TIMESTAMP,
    STARTED_AT_LOCAL TIMESTAMP NOT NULL,
    CLOSED_AT_LOCAL TIMESTAMP,
    EXPIRATION_TIME TIMESTAMP NOT NULL,
    CONSTRAINT pk_user_sessions PRIMARY KEY (SESSION_ID),
    CONSTRAINT fk_sessions_terminal_id FOREIGN KEY (TERMINAL_ID)
        REFERENCES TERMINALS(TERMINAL_ID),
    CONSTRAINT fk_sessions_user_id FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),
    CONSTRAINT fk_sessions_card_id FOREIGN KEY (CARD_ID)
        REFERENCES CARDS(CARD_ID)
);

CREATE INDEX IX_SESSIONS ON USER_SESSIONS(SESSION_ID, USER_ID);
CREATE INDEX IX_SESSIONS_USERS ON USER_SESSIONS(USER_ID, SESSION_ID);
CREATE INDEX IX_SESSIONS_STARTED ON USER_SESSIONS(STARTED_AT, USER_ID);
CREATE INDEX IX_SESSIONS_STARTED_LOCAL ON USER_SESSIONS(STARTED_AT_LOCAL, USER_ID);
CREATE INDEX IX_SESSIONS_TERMINAL ON USER_SESSIONS(TERMINAL_ID, USER_ID);
CREATE INDEX IX_SESSIONS_CARDS ON USER_SESSIONS(CARD_ID, USER_ID);

-- 13. Коды
CREATE TABLE CODES (
    CODE_UID VARCHAR(16) NOT NULL,
    CODE_TYPE CHAR(1) NOT NULL,
    CODE_CONTENT VARCHAR(256) NOT NULL,
    ALLOWED_USAGE VARCHAR(2) NOT NULL,
    VALID_FROM TIMESTAMP NOT NULL,
    VALID_TO TIMESTAMP NOT NULL,
    CONSTRAINT pk_codes PRIMARY KEY (CODE_UID),
    CONSTRAINT chk_codes_type CHECK (CODE_TYPE IN ('A', 'S')),
    CONSTRAINT chk_codes_usage CHECK (ALLOWED_USAGE IN ('RW', 'R', '-'))
);

-- 14. Мастер-пароль
CREATE TABLE MASTER_PASSWORD (
    ID BIGSERIAL NOT NULL,
    MASTER_PASSWORD_HASH VARCHAR(255),
    CONSTRAINT pk_master_password PRIMARY KEY (ID)
);

-- 15. Типы сервисных событий
CREATE TABLE SERVICE_EVENT_TYPES (
    EVENT_TYPE CHAR(2) NOT NULL,
    EVENT_TYPE_NAME VARCHAR(128) NOT NULL,
    CONSTRAINT pk_service_event_types PRIMARY KEY (EVENT_TYPE)
);

INSERT INTO SERVICE_EVENT_TYPES (EVENT_TYPE, EVENT_TYPE_NAME) VALUES
('CU', 'Создание пользователя'),
('CC', 'Создание карты'),
('RC', 'Пополнение карты'),
('DU', 'Удаление пользователя'),
('DC', 'Удаление карты'),
('TA', 'Активация терминала'),
('TD', 'Деактивация терминала'),
('DS', 'Открытие смены водителя'),
('CS', 'Закрытие смены водителя'),
('OR', 'Открыть маршрут водителем'),
('CR', 'Закрыть маршрут водителем'),
('PT', 'Оплата проезда'),
('CO', 'Открыть смену кассира'),
('CE', 'Закрыть смену кассира'),
('OE', 'Другое событие');

-- 16. Сервисные события
CREATE TABLE SERVICE_EVENTS (
    SERVICE_EVENT_ID BIGSERIAL NOT NULL,
    EVENT_TIME TIMESTAMP NOT NULL,
    EVENT_LOCAL_TIME TIMESTAMP NOT NULL,
    SERVICE_EVENT_TYPE CHAR(2) NOT NULL,
    USER_ID BIGINT,
    SESSION_ID UUID,
    REFERENCE_TYPE_ID INT,
    REFERENCE_ID BIGINT,
    EVENT_DETAILS VARCHAR(256),
    EVENT_OBJECT JSONB,
    CONSTRAINT pk_service_events PRIMARY KEY (SERVICE_EVENT_ID),
    CONSTRAINT fk_service_events_type FOREIGN KEY (SERVICE_EVENT_TYPE)
        REFERENCES SERVICE_EVENT_TYPES(EVENT_TYPE),
    CONSTRAINT fk_events_sessions_id FOREIGN KEY (SESSION_ID)
        REFERENCES USER_SESSIONS(SESSION_ID),
    CONSTRAINT fk_events_user_id FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

ALTER SEQUENCE SERVICE_EVENTS_SERVICE_EVENT_ID_SEQ RESTART WITH 1000;

CREATE INDEX IX_SERVICE_EVENTS_EVENT_TIME ON SERVICE_EVENTS(EVENT_TIME, USER_ID);
CREATE INDEX IX_SERVICE_EVENTS_EVENT_LOCAL_TIME ON SERVICE_EVENTS(EVENT_LOCAL_TIME, USER_ID);
CREATE INDEX IX_SERVICE_EVENTS_USER_ID ON SERVICE_EVENTS(USER_ID, SESSION_ID);
CREATE INDEX IX_SERVICE_EVENTS_SESSION_ID ON SERVICE_EVENTS(SESSION_ID);

-- 17. Типы платежей
CREATE TABLE PAYMENT_TYPES (
    PAYMENT_TYPE_ID INT NOT NULL,
    PAYMENT_TYPE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_payment_types PRIMARY KEY (PAYMENT_TYPE_ID)
);

INSERT INTO PAYMENT_TYPES (PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME) VALUES
(1, 'Пополнение'),
(2, 'Списание');

-- 18. Результаты платежей
CREATE TABLE PAYMENT_RESULTS (
    PAYMENT_RESULT_ID INT NOT NULL,
    PAYMENT_RESULT_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_payment_results PRIMARY KEY (PAYMENT_RESULT_ID)
);

INSERT INTO PAYMENT_RESULTS (PAYMENT_RESULT_ID, PAYMENT_RESULT_NAME) VALUES
(11, 'Успех'),
(12, 'Ошибка - карта не читается'),
(13, 'Ошибка - недостаточно средств'),
(14, 'Ошибка - карта заблокирована');

-- 19. Платежи
CREATE TABLE PAYMENTS (
    PAYMENT_ID BIGSERIAL NOT NULL,
    PAYMENT_TIME TIMESTAMP NOT NULL,
    CARD_ID BIGINT NOT NULL,
    BALANCE_BEFORE NUMERIC(19,2) NOT NULL,
    BALANCE_AFTER NUMERIC(19,2) NOT NULL,
    PAYMENT_TYPE_ID INT NOT NULL,
    PAYMENT_RESULT_ID INT NOT NULL,
    TERMINAL_ID BIGINT NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT fk_payments_card FOREIGN KEY (CARD_ID)
        REFERENCES CARDS(CARD_ID),
    CONSTRAINT fk_payments_terminal FOREIGN KEY (TERMINAL_ID)
        REFERENCES TERMINALS(TERMINAL_ID),
    CONSTRAINT fk_payments_type FOREIGN KEY (PAYMENT_TYPE_ID)
        REFERENCES PAYMENT_TYPES(PAYMENT_TYPE_ID),
    CONSTRAINT fk_payments_result FOREIGN KEY (PAYMENT_RESULT_ID)
        REFERENCES PAYMENT_RESULTS(PAYMENT_RESULT_ID)
);

ALTER SEQUENCE PAYMENTS_PAYMENT_ID_SEQ RESTART WITH 1000;

CREATE INDEX idx_payments_card_id ON PAYMENTS(CARD_ID);
CREATE INDEX idx_payments_terminal_id ON PAYMENTS(TERMINAL_ID);

-- 20. Типы маршрутов
CREATE TABLE ROUTE_TYPES (
    ROUTE_TYPES_ID BIGINT NOT NULL,
    ROUTE_TYPES_NAME VARCHAR(16) NOT NULL,
    CONSTRAINT pk_route_types PRIMARY KEY (ROUTE_TYPES_ID)
);

INSERT INTO ROUTE_TYPES (ROUTE_TYPES_ID, ROUTE_TYPES_NAME) VALUES
(1, 'Маршрут'),
(2, 'Путь');

-- 21. Маршруты
CREATE TABLE ROUTES (
    ROUTE_ID BIGSERIAL NOT NULL,
    ROUTE_GUID UUID NOT NULL,
    ROUTE_TYPES_ID BIGINT NOT NULL,
    PARENT_ROUTE_ID BIGINT,
    ROUTE_NAME VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(512),
    ROUTE_OBJECT JSONB,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT pk_routes PRIMARY KEY (ROUTE_ID),
    CONSTRAINT uq_routes_guid UNIQUE (ROUTE_GUID),
    CONSTRAINT fk_routes_route_types_id FOREIGN KEY (ROUTE_TYPES_ID)
        REFERENCES ROUTE_TYPES(ROUTE_TYPES_ID),
    CONSTRAINT fk_routes_parent_route_id FOREIGN KEY (PARENT_ROUTE_ID)
        REFERENCES ROUTES(ROUTE_ID)
);

ALTER SEQUENCE ROUTES_ROUTE_ID_SEQ RESTART WITH 1000;

CREATE INDEX IDX_ROUTES_ROUTE_GUID ON ROUTES(ROUTE_GUID);
CREATE INDEX IDX_ROUTES_PARENT_ROUTE_ID ON ROUTES(PARENT_ROUTE_ID);
CREATE INDEX IDX_ROUTES_CREATED_AT ON ROUTES(CREATED_AT);
CREATE INDEX IDX_ROUTES_UPDATED_AT ON ROUTES(UPDATED_AT);

-- 22. Привязка маршрутов к перевозчикам
CREATE TABLE CARRIER_ROUTE_MAP (
    CARRIER_ROUTE_MAP_ID BIGSERIAL NOT NULL,
    CARRIER_ID BIGINT NOT NULL,
    ROUTE_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT pk_carrier_route_map PRIMARY KEY (CARRIER_ROUTE_MAP_ID),
    CONSTRAINT fk_carrier_route_map_carrier_id FOREIGN KEY (CARRIER_ID)
        REFERENCES CARRIERS(CARRIER_ID),
    CONSTRAINT fk_carrier_route_map_route_id FOREIGN KEY (ROUTE_ID)
        REFERENCES ROUTES(ROUTE_ID)
);

ALTER SEQUENCE CARRIER_ROUTE_MAP_CARRIER_ROUTE_MAP_ID_SEQ RESTART WITH 1000;

CREATE INDEX IDX_CARRIER_ROUTE_MAP_CARRIER_ID ON CARRIER_ROUTE_MAP(CARRIER_ID);
CREATE INDEX IDX_CARRIER_ROUTE_MAP_ROUTE_ID ON CARRIER_ROUTE_MAP(ROUTE_ID);
CREATE INDEX IDX_CARRIER_ROUTE_MAP_CREATED_AT ON CARRIER_ROUTE_MAP(CREATED_AT);
CREATE INDEX IDX_CARRIER_ROUTE_MAP_UPDATED_AT ON CARRIER_ROUTE_MAP(UPDATED_AT);
CREATE UNIQUE INDEX UK_CARRIER_ROUTE_MAP_CARRIER_ROUTE ON CARRIER_ROUTE_MAP(CARRIER_ID, ROUTE_ID);

-- 23. Тарифные зоны
CREATE TABLE FARE_ZONES (
    ZONE_ID BIGSERIAL NOT NULL,
    ZONE_CODE VARCHAR(20) NOT NULL,
    ZONE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(256),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT pk_fare_zones PRIMARY KEY (ZONE_ID),
    CONSTRAINT uq_fare_zones_code UNIQUE (ZONE_CODE)
);

ALTER SEQUENCE FARE_ZONES_ZONE_ID_SEQ RESTART WITH 1000;

CREATE INDEX IDX_FARE_ZONES_CREATED_AT ON FARE_ZONES(CREATED_AT);
CREATE INDEX IDX_FARE_ZONES_UPDATED_AT ON FARE_ZONES(UPDATED_AT);

-- 24. Тарифы перевозчика по зонам
CREATE TABLE CARRIER_ZONE_MAP (
    CARRIER_ZONE_MAP_ID BIGSERIAL NOT NULL,
    CARRIER_ID BIGINT NOT NULL,
    ZONE_ID BIGINT NOT NULL,
    BASE_FARE DECIMAL(10,2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT pk_carrier_zone_map PRIMARY KEY (CARRIER_ZONE_MAP_ID),
    CONSTRAINT fk_carrier_zone_map_carrier_id FOREIGN KEY (CARRIER_ID)
        REFERENCES CARRIERS(CARRIER_ID),
    CONSTRAINT fk_carrier_zone_map_zone_id FOREIGN KEY (ZONE_ID)
        REFERENCES FARE_ZONES(ZONE_ID)
);

ALTER SEQUENCE CARRIER_ZONE_MAP_CARRIER_ZONE_MAP_ID_SEQ RESTART WITH 1000;

CREATE INDEX IDX_CARRIER_ZONE_MAP_CARRIER_ID ON CARRIER_ZONE_MAP(CARRIER_ID);
CREATE INDEX IDX_CARRIER_ZONE_MAP_ZONE_ID ON CARRIER_ZONE_MAP(ZONE_ID);
CREATE INDEX IDX_CARRIER_ZONE_MAP_CREATED_AT ON CARRIER_ZONE_MAP(CREATED_AT);
CREATE INDEX IDX_CARRIER_ZONE_MAP_UPDATED_AT ON CARRIER_ZONE_MAP(UPDATED_AT);
CREATE UNIQUE INDEX UK_CARRIER_ZONE_MAP_CARRIER_ZONE ON CARRIER_ZONE_MAP(CARRIER_ID, ZONE_ID);

-- 25. Включение PostGIS (если нужно)
-- CREATE EXTENSION IF NOT EXISTS postgis;

-- 26. Остановки транспорта
CREATE TABLE TRANSPORT_STOPS (
    STOP_ID BIGSERIAL NOT NULL,
    FARE_ZONE_ID BIGINT NOT NULL,
    STOP_CODE VARCHAR(20) NOT NULL,
    STOP_NAME VARCHAR(200) NOT NULL,
    STOP_ADDRESS VARCHAR(500),
    GEO_LOCATION GEOGRAPHY(POINT, 4326),
    DESCRIPTION TEXT,
    IS_ACTIVE BOOLEAN DEFAULT true,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT pk_transport_stops PRIMARY KEY (STOP_ID),
    CONSTRAINT uq_transport_stops_code UNIQUE (STOP_CODE),
    CONSTRAINT fk_transport_stops_fare_zone_id FOREIGN KEY (FARE_ZONE_ID)
        REFERENCES FARE_ZONES(ZONE_ID)
);

ALTER SEQUENCE TRANSPORT_STOPS_STOP_ID_SEQ RESTART WITH 1000;

CREATE INDEX IDX_TRANSPORT_STOPS_FARE_ZONE_ID ON TRANSPORT_STOPS(FARE_ZONE_ID);
CREATE INDEX IDX_TRANSPORT_STOPS_GEO_LOCATION ON TRANSPORT_STOPS USING GIST (GEO_LOCATION);
CREATE INDEX IDX_TRANSPORT_STOPS_CREATED_AT ON TRANSPORT_STOPS(CREATED_AT);
CREATE INDEX IDX_TRANSPORT_STOPS_UPDATED_AT ON TRANSPORT_STOPS(UPDATED_AT);

-- 27. Привязка остановок к маршрутам
CREATE TABLE STOPS_ROUTE_MAP (
    STOPS_ROUTE_MAP_ID BIGSERIAL NOT NULL,
    STOP_ID BIGINT NOT NULL,
    ROUTE_ID BIGINT NOT NULL,
    SERIAL_NUMBER INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT pk_stops_route_map PRIMARY KEY (STOPS_ROUTE_MAP_ID),
    CONSTRAINT fk_stops_route_map_stop_id FOREIGN KEY (STOP_ID)
        REFERENCES TRANSPORT_STOPS(STOP_ID),
    CONSTRAINT fk_stops_route_map_route_id FOREIGN KEY (ROUTE_ID)
        REFERENCES ROUTES(ROUTE_ID)
);

ALTER SEQUENCE STOPS_ROUTE_MAP_STOPS_ROUTE_MAP_ID_SEQ RESTART WITH 1000;

CREATE INDEX IDX_STOPS_ROUTE_MAP_CREATED_AT ON STOPS_ROUTE_MAP(CREATED_AT);
CREATE INDEX IDX_STOPS_ROUTE_MAP_UPDATED_AT ON STOPS_ROUTE_MAP(UPDATED_AT);
CREATE UNIQUE INDEX UK_STOPS_ROUTE_MAP_ROUTE_STOP ON STOPS_ROUTE_MAP(ROUTE_ID, STOP_ID);

-- 28. Рейсы
CREATE TABLE trips (
    TRIP_ID BIGSERIAL NOT NULL,
    ROUTE_ID BIGINT NOT NULL,
    SESSION_ID UUID NOT NULL,
    STARTED_AT TIMESTAMP NOT NULL,
    CLOSED_AT TIMESTAMP,
    STARTED_AT_LOCAL TIMESTAMP NOT NULL,
    CLOSED_AT_LOCAL TIMESTAMP,
    CONSTRAINT pk_trips PRIMARY KEY (TRIP_ID),
    CONSTRAINT fk_trips_route_id FOREIGN KEY (ROUTE_ID)
        REFERENCES ROUTES(ROUTE_ID),
    CONSTRAINT fk_trips_session_id FOREIGN KEY (SESSION_ID)
        REFERENCES USER_SESSIONS(SESSION_ID)
);

CREATE INDEX IDX_trips_STARTED_AT ON trips(STARTED_AT);
CREATE INDEX IDX_trips_STARTED_AT_LOCAL ON trips(STARTED_AT_LOCAL);

-- 29. Привязка остановок к тарифным зонам
CREATE TABLE STOPS_ZONE_MAP (
    STOPS_ZONE_MAP_ID BIGSERIAL NOT NULL,
    STOP_ID BIGINT NOT NULL,
    ZONE_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT pk_stops_zone_map PRIMARY KEY (STOPS_ZONE_MAP_ID),
    CONSTRAINT fk_stops_zone_map_stop_id FOREIGN KEY (STOP_ID)
        REFERENCES TRANSPORT_STOPS(STOP_ID),
    CONSTRAINT fk_stops_zone_map_zone_id FOREIGN KEY (ZONE_ID)
        REFERENCES FARE_ZONES(ZONE_ID)
);

ALTER SEQUENCE STOPS_ZONE_MAP_STOPS_ZONE_MAP_ID_SEQ RESTART WITH 1000;

CREATE INDEX IDX_STOPS_ZONE_MAP_CREATED_AT ON STOPS_ZONE_MAP(CREATED_AT);
CREATE INDEX IDX_STOPS_ZONE_MAP_UPDATED_AT ON STOPS_ZONE_MAP(UPDATED_AT);
CREATE INDEX IDX_STOPS_ZONE_MAP_STOP_ID ON STOPS_ZONE_MAP(STOP_ID);
CREATE INDEX IDX_STOPS_ZONE_MAP_ZONE_ID ON STOPS_ZONE_MAP(ZONE_ID);
CREATE UNIQUE INDEX UK_STOPS_ZONE_MAP_STOP_ZONE ON STOPS_ZONE_MAP(STOP_ID, ZONE_ID);

-- ============================================================
-- КОММЕНТАРИИ К ТАБЛИЦАМ (для документации)
-- ============================================================

COMMENT ON TABLE SERVICE_EVENTS IS 'Таблица для хранения сервисных событий. Колонка EVENT_OBJECT имеет тип JSONB для хранения структурированных данных событий.';

-- ============================================================
-- СОВЕТЫ ПО ИСПОЛЬЗОВАНИЮ:
-- 1. Сохраните этот скрипт в файл create_tavrida_database.sql
-- 2. Выполните в psql: \i /путь/к/файлу/create_tavrida_database.sql
-- 3. Или через командную строку:
--    psql -U username -d database_name -f create_tavrida_database.sql
-- ============================================================