-- ========= НОВЫЕ ТАБЛИЦЫ =========

-- 1. Сессии пользователей
CREATE TABLE USER_SESSIONS (
    SESSION_ID      UUID      NOT NULL PRIMARY KEY,
    USER_ID         BIGINT    NOT NULL,  -- соответствует USERS.USER_ID (BIGINT)
    EXPIRATION_TIME TIMESTAMP NOT NULL
);
CREATE INDEX IX_SESSIONS ON USER_SESSIONS (SESSION_ID, USER_ID, EXPIRATION_TIME);

-- 2. Коды (ключи)
CREATE TABLE CODES (
    CODE_UID       VARCHAR(16)  NOT NULL PRIMARY KEY,
    CODE_TYPE      CHAR(1)      NOT NULL CHECK (CODE_TYPE IN ('A','S')),
    CODE_CONTENT   VARCHAR(256) NOT NULL,
    ALLOWED_USAGE  VARCHAR(2)   NOT NULL CHECK (ALLOWED_USAGE IN ('RW','R','-')),
    VALID_FROM     TIMESTAMP    NOT NULL,
    VALID_TO       TIMESTAMP    NOT NULL
);

-- 3. Мастер-пароль
CREATE TABLE MASTER_PASSWORD (
    MASTER_PASSWORD_HASH VARCHAR(255)
);

-- 4. Типы событий аудита
CREATE TABLE SERVICE_EVENT_TYPES (
    EVENT_TYPE      CHAR(2)      PRIMARY KEY,
    EVENT_TYPE_NAME VARCHAR(128) NOT NULL
);
INSERT INTO SERVICE_EVENT_TYPES (EVENT_TYPE, EVENT_TYPE_NAME) VALUES
    ('CU', 'Создание пользователя'),
    ('CC', 'Создание карты'),
    ('DU', 'Удаление пользователя'),
    ('DC', 'Удаление карты'),
    ('OE', 'Другое событие');

-- 5. События аудита
CREATE TABLE SERVICE_EVENTS (
    SERVICE_EVENT_ID   SERIAL       PRIMARY KEY,
    EVENT_TIME         TIMESTAMP    NOT NULL,
    SERVICE_EVENT_TYPE CHAR(2)      NOT NULL REFERENCES SERVICE_EVENT_TYPES(EVENT_TYPE),
    DOER_USER_ID       BIGINT       NULL,
    REFERENCE_TYPE_ID  INT          NULL,
    REFERENCE_ID       BIGINT       NULL,
    EVENT_DETAILS      VARCHAR(256) NULL
);

-- 6. Типы платежей
CREATE TABLE PAYMENT_TYPES (
    PAYMENT_TYPE_ID   INT         NOT NULL PRIMARY KEY,
    PAYMENT_TYPE_NAME VARCHAR(255) NOT NULL
);
INSERT INTO PAYMENT_TYPES (PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME) VALUES
    (1, 'Пополнение'),
    (2, 'Списание');

-- 7. Результаты платежей
CREATE TABLE PAYMENT_RESULTS (
    PAYMENT_RESULT_ID   INT         NOT NULL PRIMARY KEY,
    PAYMENT_RESULT_NAME VARCHAR(255) NOT NULL
);
INSERT INTO PAYMENT_RESULTS (PAYMENT_RESULT_ID, PAYMENT_RESULT_NAME) VALUES
    (11, 'Успех'),
    (12, 'Ошибка - карта не читается'),
    (13, 'Ошибка - недостаточно средств'),
    (14, 'Ошибка - карта заблокирована');

-- 8. Платежи
CREATE TABLE PAYMENTS (
    PAYMENT_ID        BIGSERIAL    PRIMARY KEY,
    PAYMENT_TIME      TIMESTAMP    NOT NULL,
    CARD_ID           BIGINT       NOT NULL,
    BALANCE_BEFORE    NUMERIC(19,2) NOT NULL,
    BALANCE_AFTER     NUMERIC(19,2) NOT NULL,
    PAYMENT_TYPE_ID   INT          NOT NULL,
    PAYMENT_RESULT_ID INT          NOT NULL,
    TERMINAL_ID       BIGINT       NOT NULL
);

-- Внешние ключи для PAYMENTS
ALTER TABLE PAYMENTS
    ADD CONSTRAINT fk_payments_card
    FOREIGN KEY (CARD_ID) REFERENCES CARDS(CARD_ID);

ALTER TABLE PAYMENTS
    ADD CONSTRAINT fk_payments_terminal
    FOREIGN KEY (TERMINAL_ID) REFERENCES TERMINALS(TERMINAL_ID);

ALTER TABLE PAYMENTS
    ADD CONSTRAINT fk_payments_type
    FOREIGN KEY (PAYMENT_TYPE_ID) REFERENCES PAYMENT_TYPES(PAYMENT_TYPE_ID);

ALTER TABLE PAYMENTS
    ADD CONSTRAINT fk_payments_result
    FOREIGN KEY (PAYMENT_RESULT_ID) REFERENCES PAYMENT_RESULTS(PAYMENT_RESULT_ID);

-- Индексы для производительности
CREATE INDEX idx_payments_card_id ON PAYMENTS (CARD_ID);
CREATE INDEX idx_payments_terminal_id ON PAYMENTS (TERMINAL_ID);
CREATE INDEX idx_service_events_doer ON SERVICE_EVENTS (DOER_USER_ID);