-- 1. Справочник ролей пользователей
CREATE TABLE USER_ROLES (
    USER_ROLE_ID INT NOT NULL,
    USER_ROLE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT USER_ROLES_pkey PRIMARY KEY (USER_ROLE_ID)
);

INSERT INTO USER_ROLES (USER_ROLE_ID, USER_ROLE_NAME) VALUES
    (1, 'Администратор оператора денежных средств'),
    (2, 'Администратор перевозчика'),
    (3, 'Кассир'),
    (4, 'Водитель');

-- 2. Справочник типов карт
CREATE TABLE CARD_TYPES (
    CARD_TYPE_ID INT NOT NULL,
    CARD_TYPE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT CARD_TYPES_pkey PRIMARY KEY (CARD_TYPE_ID)
);

INSERT INTO CARD_TYPES (CARD_TYPE_ID, CARD_TYPE_NAME) VALUES
    (1, 'Карта сотрудника'),
    (2, 'Карта для настройки терминала'),
    (3, 'Карта сброса терминала'),
    (4, 'Карта пассажира');

-- 3. Перевозчики
CREATE TABLE CARRIERS (
    CARRIER_ID BIGSERIAL NOT NULL,
    CARRIER_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT CARRIERS_pkey PRIMARY KEY (CARRIER_ID)
);

-- 4. Пользователи
CREATE TABLE USERS (
    USER_ID BIGSERIAL NOT NULL,
    USER_ROLE_ID INT NOT NULL,
    USER_FIO VARCHAR(255),
    CARRIER_ID BIGINT,
    USER_PASSWORD_HASH VARCHAR(255),
    CONSTRAINT USERS_pkey PRIMARY KEY (USER_ID)
);

ALTER TABLE USERS
    ADD CONSTRAINT fk_users_user_role_id
    FOREIGN KEY (USER_ROLE_ID) REFERENCES USER_ROLES(USER_ROLE_ID);

ALTER TABLE USERS
    ADD CONSTRAINT fk_users_carrier_id
    FOREIGN KEY (CARRIER_ID) REFERENCES CARRIERS(CARRIER_ID);

INSERT INTO USERS (USER_ID, USER_ROLE_ID, USER_FIO, USER_PASSWORD_HASH) VALUES
    (1, 1, 'Алексей Петрович Свиридюк', 'FIRST_PASSWORD');

-- 5. Транспорт
CREATE TABLE TRANSPORTS (
    TRANSPORT_ID BIGSERIAL NOT NULL,
    TRANSPORT_GUID UUID NOT NULL UNIQUE,
    CARRIER_ID BIGINT NOT NULL,
    TRANSPORT_NUMBER VARCHAR(16) NOT NULL,
    TRANSPORT_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT TRANSPORTS_pkey PRIMARY KEY (TRANSPORT_ID)
);

ALTER TABLE TRANSPORTS
    ADD CONSTRAINT fk_transports_carrier_id
    FOREIGN KEY (CARRIER_ID) REFERENCES CARRIERS(CARRIER_ID);

-- 6. Терминалы
CREATE TABLE TERMINALS (
    TERMINAL_ID BIGSERIAL NOT NULL,
    TRANSPORT_ID BIGINT NOT NULL,
    TERMINAL_GUID UUID NOT NULL UNIQUE,
    TERMINAL_NUMBER VARCHAR(16) NOT NULL,
    CONSTRAINT TERMINALS_pkey PRIMARY KEY (TERMINAL_ID)
);

ALTER TABLE TERMINALS
    ADD CONSTRAINT fk_terminals_transport_id
    FOREIGN KEY (TRANSPORT_ID) REFERENCES TRANSPORTS(TRANSPORT_ID);

-- 7. Карты
CREATE TABLE CARDS (
    CARD_ID BIGSERIAL NOT NULL,
    CARD_GUID UUID NOT NULL UNIQUE,
    CARD_TYPE_ID INT NOT NULL,
    USER_ID BIGINT,
    UNIQUE_TRAVEL_COUNT INT NOT NULL,
    MAXIMUM_UNIQUE_COUNT INT NOT NULL,
    AVAILABLE_TRAVEL_COUNT INT NOT NULL,
    EXPIRATION_DATE TIMESTAMP WITH TIME ZONE,
    CONSTRAINT CARDS_pkey PRIMARY KEY (CARD_ID)
);

ALTER TABLE CARDS
    ADD CONSTRAINT fk_cards_card_type_id
    FOREIGN KEY (CARD_TYPE_ID) REFERENCES CARD_TYPES(CARD_TYPE_ID);

ALTER TABLE CARDS
    ADD CONSTRAINT fk_cards_user_id
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

-- CHECK-ограничение для таблицы CARDS
ALTER TABLE CARDS
ADD CONSTRAINT chk_cards_travel_count
CHECK (AVAILABLE_TRAVEL_COUNT >= 0 AND AVAILABLE_TRAVEL_COUNT <= MAXIMUM_UNIQUE_COUNT);

-- 8. Чёрный список
CREATE TABLE BLACK_LIST (
    CARD_GUID UUID NOT NULL UNIQUE
);

-- 9. Индексы для производительности
CREATE INDEX idx_cards_guid ON CARDS (CARD_GUID);
CREATE INDEX idx_blacklist_guid ON BLACK_LIST (CARD_GUID);
CREATE INDEX idx_terminals_guid ON TERMINALS (TERMINAL_GUID);