-- USER_SESSIONS
CREATE TABLE USER_SESSIONS (
    SESSION_ID UUID NOT NULL PRIMARY KEY,
    TERMINAL_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    SESSIONS_TIME TIMESTAMP NOT NULL,
    EXPIRATION_TIME TIMESTAMP NOT NULL
);
CREATE INDEX IX_SESSIONS ON USER_SESSIONS (SESSION_ID, USER_ID);
ALTER TABLE USER_SESSIONS
    ADD CONSTRAINT fk_sessions_terminal_id
    FOREIGN KEY (TERMINAL_ID) REFERENCES TERMINALS(terminal_id);
ALTER TABLE USER_SESSIONS
    ADD CONSTRAINT fk_sessions_user_id
    FOREIGN KEY (USER_ID) REFERENCES USERS(user_id);

-- CODES
CREATE TABLE CODES (
    CODE_UID VARCHAR(16) NOT NULL PRIMARY KEY,
    CODE_TYPE CHAR(1) NOT NULL,
    CODE_CONTENT VARCHAR(256) NOT NULL,
    ALLOWED_USAGE VARCHAR(2) NOT NULL,
    VALID_FROM TIMESTAMP NOT NULL,
    VALID_TO TIMESTAMP NOT NULL
);
ALTER TABLE CODES ADD CONSTRAINT chk_codes_type CHECK (CODE_TYPE IN ('A', 'S'));
ALTER TABLE CODES ADD CONSTRAINT chk_codes_usage CHECK (ALLOWED_USAGE IN ('RW', 'R', '-'));

-- MASTER_PASSWORD
CREATE TABLE MASTER_PASSWORD (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    MASTER_PASSWORD_HASH VARCHAR(255)
);

-- SERVICE_EVENT_TYPES
CREATE TABLE SERVICE_EVENT_TYPES (
    EVENT_TYPE CHAR(2) NOT NULL PRIMARY KEY,
    EVENT_TYPE_NAME VARCHAR(128) NOT NULL
);
INSERT INTO SERVICE_EVENT_TYPES (EVENT_TYPE, EVENT_TYPE_NAME) VALUES
    ('CU', 'Создание пользователя'),     -- C + U (Create User)
    ('CC', 'Создание карты'),            -- C + C (Create Card)
    ('DU', 'Удаление пользователя'),     -- D + U (Delete User)
    ('DC', 'Удаление карты'),            -- D + C (Delete Card)
    ('TA', 'Активация терминала'),       -- T + A (Terminal Activation)
    ('TD', 'Деактивация терминала'),     -- T + D (Terminal Deactivation)
    ('DS', 'Открытие смены водителя'),   -- D + S (Driver Shift) или (Drive Shift)
    ('PT', 'Оплата проезда'),            -- P + T (Payment for Transit / Payment Trip)
    ('OE', 'Другое событие');            -- O + E (Other Event)

-- SERVICE_EVENTS
CREATE TABLE SERVICE_EVENTS (
    SERVICE_EVENT_ID BIGSERIAL NOT NULL PRIMARY KEY,
    EVENT_TIME TIMESTAMP NOT NULL,
    SERVICE_EVENT_TYPE CHAR(2) NOT NULL,
    DOER_USER_ID BIGINT,
    REFERENCE_TYPE_ID INT,
    REFERENCE_ID BIGINT,
    EVENT_DETAILS VARCHAR(256),
    EVENT_OBJECT JSONB
);
ALTER TABLE SERVICE_EVENTS
    ADD CONSTRAINT fk_service_events_type
    FOREIGN KEY (SERVICE_EVENT_TYPE) REFERENCES SERVICE_EVENT_TYPES(EVENT_TYPE);

-- PAYMENT_TYPES
CREATE TABLE PAYMENT_TYPES (
    PAYMENT_TYPE_ID INT NOT NULL PRIMARY KEY,
    PAYMENT_TYPE_NAME VARCHAR(255) NOT NULL
);
INSERT INTO PAYMENT_TYPES (PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME) VALUES
    (1, 'Пополнение'),
    (2, 'Списание');

-- PAYMENT_RESULTS
CREATE TABLE PAYMENT_RESULTS (
    PAYMENT_RESULT_ID INT NOT NULL PRIMARY KEY,
    PAYMENT_RESULT_NAME VARCHAR(255) NOT NULL
);
INSERT INTO PAYMENT_RESULTS (PAYMENT_RESULT_ID, PAYMENT_RESULT_NAME) VALUES
    (11, 'Успех'),
    (12, 'Ошибка - карта не читается'),
    (13, 'Ошибка - недостаточно средств'),
    (14, 'Ошибка - карта заблокирована');

-- PAYMENTS
CREATE TABLE PAYMENTS (
    PAYMENT_ID BIGSERIAL NOT NULL PRIMARY KEY,
    PAYMENT_TIME TIMESTAMP NOT NULL,
    CARD_ID BIGINT NOT NULL,
    BALANCE_BEFORE NUMERIC(19,2) NOT NULL,
    BALANCE_AFTER NUMERIC(19,2) NOT NULL,
    PAYMENT_TYPE_ID INT NOT NULL,
    PAYMENT_RESULT_ID INT NOT NULL,
    TERMINAL_ID BIGINT NOT NULL
);
ALTER TABLE PAYMENTS
    ADD CONSTRAINT fk_payments_card
    FOREIGN KEY (CARD_ID) REFERENCES CARDS(CARD_ID);
ALTER TABLE PAYMENTS
    ADD CONSTRAINT fk_payments_terminal
    FOREIGN KEY (TERMINAL_ID) REFERENCES TERMINALS(TERMINAL_ID);
ALTER TABLE PAYMENTS
    ADD CONSTRAINT fk_payments_type
    FOREIGN KEY (PAYMENT_TYPE_ID) REFERENCES PAYMENT_TYPES(PAYMENT_TYPE_ID);
ALTER TABLE PAYMENTS
    ADD CONSTRAINT fk_payments_result
    FOREIGN KEY (PAYMENT_RESULT_ID) REFERENCES PAYMENT_RESULTS(PAYMENT_RESULT_ID);
CREATE INDEX idx_payments_card_id ON PAYMENTS (CARD_ID);
CREATE INDEX idx_payments_terminal_id ON PAYMENTS (TERMINAL_ID);