-- 1. Справочник ролей пользователей
CREATE TABLE USER_ROLES (
    USER_ROLE_ID INT NOT NULL,
    USER_ROLE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT USER_ROLES_pkey PRIMARY KEY (USER_ROLE_ID)
);

INSERT INTO USER_ROLES (USER_ROLE_ID, USER_ROLE_NAME) VALUES
    (1, 'Администратор'),
    (2, 'Администратор перевозчика'),
    (3, 'Кассир'),
    (4, 'Водитель');

-- 2. Справочник типов карт
CREATE TABLE CARD_TYPES (
    CARD_TYPE_ID INT NOT NULL,
    CARD_TYPE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT CARD_TYPES_pkey PRIMARY KEY (CARD_TYPE_ID)
);

INSERT INTO CARD_TYPES (CARD_TYPE_ID, CARD_TYPE_NAME) VALUES
    (1, 'Карта администратора'),
    (2, 'Карта кассира'),
    (3, 'Карта водителя'),
    (4, 'Карта пассажира'),
    (5, 'Карта активации терминала');
    (6, 'Карта сброса терминала');

-- 3. Перевозчики
CREATE TABLE CARRIERS (
    CARRIER_ID BIGSERIAL NOT NULL,
    CARRIER_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT CARRIERS_pkey PRIMARY KEY (CARRIER_ID)
);

INSERT INTO CARRIERS (CARRIER_ID, CARRIER_NAME) VALUES
    (1, 'Крымские трамваи');

-- 4. Пользователи
CREATE TABLE USERS (
    USER_ID BIGSERIAL NOT NULL,
    USER_ROLE_ID INT NOT NULL,
    USER_FIO VARCHAR(255),
    CARRIER_ID BIGINT,
    USER_PASSWORD_HASH VARCHAR(255),
    CONSTRAINT USERS_pkey PRIMARY KEY (USER_ID)
);

ALTER TABLE USERS
    ADD CONSTRAINT fk_users_user_role_id
    FOREIGN KEY (USER_ROLE_ID) REFERENCES USER_ROLES(USER_ROLE_ID);

ALTER TABLE USERS
    ADD CONSTRAINT fk_users_carrier_id
    FOREIGN KEY (CARRIER_ID) REFERENCES CARRIERS(CARRIER_ID);

INSERT INTO USERS (USER_ID, USER_ROLE_ID, USER_FIO, USER_PASSWORD_HASH) VALUES
    (1, 3, 'Алексей Петрович Свиридюк', 'FIRST_PASSWORD');

-- 5. Транспорт
CREATE TABLE TRANSPORTS (
    TRANSPORT_ID BIGSERIAL NOT NULL,
    TRANSPORT_GUID UUID NOT NULL UNIQUE,
    CARRIER_ID BIGINT NOT NULL,
    TRANSPORT_NUMBER VARCHAR(16) NOT NULL,
    TRANSPORT_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT TRANSPORTS_pkey PRIMARY KEY (TRANSPORT_ID)
);

ALTER TABLE TRANSPORTS
    ADD CONSTRAINT fk_transports_carrier_id
    FOREIGN KEY (CARRIER_ID) REFERENCES CARRIERS(CARRIER_ID);

INSERT INTO TRANSPORTS (TRANSPORT_ID, TRANSPORT_GUID, CARRIER_ID, TRANSPORT_NUMBER, TRANSPORT_NAME) VALUES
    (1, '264bfe9d-98c5-4cfc-a27b-9b6234054580', 1, '1', 'трамвай');

-- 6. Терминалы
CREATE TABLE TERMINALS (
    TERMINAL_ID BIGSERIAL NOT NULL,
    TRANSPORT_ID BIGINT,
    TERMINAL_GUID UUID NOT NULL UNIQUE,
    TERMINAL_NUMBER VARCHAR(16) NOT NULL,
    CONSTRAINT TERMINALS_pkey PRIMARY KEY (TERMINAL_ID)
);

ALTER TABLE TERMINALS
    ADD CONSTRAINT fk_terminals_transport_id
    FOREIGN KEY (TRANSPORT_ID) REFERENCES TRANSPORTS(TRANSPORT_ID);

INSERT INTO TERMINALS (TERMINAL_ID, TRANSPORT_ID, TERMINAL_GUID, TERMINAL_NUMBER) VALUES
    (1, 1, '3f2dd185-0540-4d82-ad26-e6a181cb1893', '1234567890123456');

-- 7. Карты
CREATE TABLE CARDS (
    CARD_ID BIGSERIAL NOT NULL,
    CARD_GUID UUID NOT NULL UNIQUE,
    CARD_TYPE_ID INT NOT NULL,
    USER_ID BIGINT,
    TRANSPORT_ID BIGINT,
    UNIQUE_TRAVEL_COUNT INT NOT NULL,
    MAXIMUM_UNIQUE_COUNT INT NOT NULL,
    AVAILABLE_TRAVEL_COUNT INT NOT NULL,
    ISSUE_DATE TIMESTAMP,
    EXPIRATION_DATE TIMESTAMP,
    CONSTRAINT CARDS_pkey PRIMARY KEY (CARD_ID)
);

ALTER TABLE CARDS
    ADD CONSTRAINT fk_cards_transport_id
    FOREIGN KEY (TRANSPORT_ID) REFERENCES TRANSPORTS(TRANSPORT_ID);

ALTER TABLE CARDS
    ADD CONSTRAINT fk_cards_card_type_id
    FOREIGN KEY (CARD_TYPE_ID) REFERENCES CARD_TYPES(CARD_TYPE_ID);

ALTER TABLE CARDS
    ADD CONSTRAINT fk_cards_user_id
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

INSERT INTO CARDS (
    CARD_ID,
    CARD_GUID,
    CARD_TYPE_ID,
    USER_ID,
    TRANSPORT_ID,
    UNIQUE_TRAVEL_COUNT,
    MAXIMUM_UNIQUE_COUNT,
    AVAILABLE_TRAVEL_COUNT,
    ISSUE_DATE,
    EXPIRATION_DATE
) VALUES (
    1,
    '123e4567-e89b-42d3-a456-556642440000',
    4,
    1,
    0,
    10000,
    1000,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '3 years'
);

-- CHECK-ограничение для таблицы CARDS
ALTER TABLE CARDS
ADD CONSTRAINT chk_cards_travel_count
CHECK (AVAILABLE_TRAVEL_COUNT >= 0);

-- 8. Чёрный список
CREATE TABLE BLACK_LIST (
    CARD_GUID UUID NOT NULL UNIQUE
);

-- 9. Индексы для производительности
CREATE INDEX idx_cards_guid ON CARDS (CARD_GUID);
CREATE INDEX idx_blacklist_guid ON BLACK_LIST (CARD_GUID);
CREATE INDEX idx_terminals_guid ON TERMINALS (TERMINAL_GUID);