-- 1. Справочник ролей пользователей
CREATE TABLE USER_ROLES (
    USER_ROLE_ID INT NOT NULL,
    USER_ROLE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT USER_ROLES_pkey PRIMARY KEY (USER_ROLE_ID)
);

INSERT INTO USER_ROLES (USER_ROLE_ID, USER_ROLE_NAME) VALUES
    (1, 'Администратор'),
    (2, 'Администратор перевозчика'),
    (3, 'Кассир'),
    (4, 'Водитель');

-- 2. Справочник типов карт
CREATE TABLE CARD_TYPES (
    CARD_TYPE_ID INT NOT NULL,
    CARD_TYPE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT CARD_TYPES_pkey PRIMARY KEY (CARD_TYPE_ID)
);

INSERT INTO CARD_TYPES (CARD_TYPE_ID, CARD_TYPE_NAME) VALUES
    (1, 'Карта администратора'),
    (2, 'Карта кассира'),
    (3, 'Карта водителя'),
    (4, 'Карта пассажира'),
    (5, 'Карта активации терминала'),
    (6, 'Карта сброса терминала');

-- 3. Перевозчики
CREATE TABLE CARRIERS (
    CARRIER_ID BIGSERIAL NOT NULL,
    CARRIER_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT CARRIERS_pkey PRIMARY KEY (CARRIER_ID)
);
ALTER SEQUENCE CARRIERS_CARRIER_ID_seq
RESTART WITH 1000;

-- 4. Пользователи
CREATE TABLE USERS (
    USER_ID BIGSERIAL NOT NULL,
    USER_ROLE_ID INT NOT NULL,
    USER_FIO VARCHAR(255),
    CARRIER_ID BIGINT,
    USER_PASSWORD_HASH VARCHAR(255),
    CONSTRAINT USERS_pkey PRIMARY KEY (USER_ID)
);
ALTER SEQUENCE USERS_USER_ID_seq
RESTART WITH 1000;

ALTER TABLE USERS
    ADD CONSTRAINT fk_users_user_role_id
    FOREIGN KEY (USER_ROLE_ID) REFERENCES USER_ROLES(USER_ROLE_ID);

ALTER TABLE USERS
    ADD CONSTRAINT fk_users_carrier_id
    FOREIGN KEY (CARRIER_ID) REFERENCES CARRIERS(CARRIER_ID);

-- 5. Транспорт
CREATE TABLE TRANSPORTS (
    TRANSPORT_ID BIGSERIAL NOT NULL,
    TRANSPORT_GUID UUID NOT NULL UNIQUE,
    CARRIER_ID BIGINT NOT NULL,
    TRANSPORT_NUMBER VARCHAR(16) NOT NULL,
    TRANSPORT_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT TRANSPORTS_pkey PRIMARY KEY (TRANSPORT_ID)
);
ALTER SEQUENCE TRANSPORTS_TRANSPORT_ID_seq
RESTART WITH 1000;

ALTER TABLE TRANSPORTS
    ADD CONSTRAINT fk_transports_carrier_id
    FOREIGN KEY (CARRIER_ID) REFERENCES CARRIERS(CARRIER_ID);

-- 6. Терминалы
CREATE TABLE TERMINALS (
    TERMINAL_ID BIGSERIAL NOT NULL,
    TRANSPORT_ID BIGINT,
    TERMINAL_GUID UUID NOT NULL UNIQUE,
    TERMINAL_NUMBER VARCHAR(16) NOT NULL,
    TERMINAL_SERIAL VARCHAR(64) NOT NULL,
    CONSTRAINT TERMINALS_pkey PRIMARY KEY (TERMINAL_ID)
);
ALTER SEQUENCE TERMINALS_TERMINAL_ID_seq
RESTART WITH 1000;

ALTER TABLE TERMINALS
    ADD CONSTRAINT fk_terminals_transport_id
    FOREIGN KEY (TRANSPORT_ID) REFERENCES TRANSPORTS(TRANSPORT_ID);

-- 1. ТИПЫ ТАРИФОВ (СПРАВОЧНИК)
CREATE TABLE TARIFF_TYPES (
    TARIFF_TYPE_ID INT PRIMARY KEY,
    CODE VARCHAR(50) NOT NULL UNIQUE, -- 'PAY_AS_YOU_GO', 'UNLIMITED_DAILY', '10_RIDES_PACKAGE'
    NAME VARCHAR(100) NOT NULL, -- 'ПОПОЛНЯЕМЫЙ КОШЕЛЁК', 'БЕЗЛИМИТНЫЙ НА МЕСЯЦ', 'ПАКЕТ 10 ПОЕЗДОК'
    DESCRIPTION TEXT
);

-- Тариф 1: Пакет поездок до даты (пакетный тариф)
INSERT INTO TARIFF_TYPES (TARIFF_TYPE_ID, CODE, NAME, DESCRIPTION) VALUES
(1, 'RIDES_PACKAGE', 'Пакет поездок до даты',
'Фиксированное количество поездок (например, 10 или 20), которые нужно использовать до определённой даты. Остаток поездок - в AVAILABLE_TRAVEL_COUNT, срок - в EXPIRATION_RIDES_PACKAGE карты.');

-- Тариф 1: Безлимит поездок до даты (подписка)
INSERT INTO TARIFF_TYPES (TARIFF_TYPE_ID, CODE, NAME, DESCRIPTION) VALUES
(2, 'UNLIMITED_TILL_DATE', 'Безлимит до даты',
'Безлимитное количество поездок в течение определённого периода (день/неделя/месяц/год). Срок действия указан в поле unlimited_until_date карты.');

-- Тариф 3: Пополняемый кошелёк (pay-as-you-go)
INSERT INTO TARIFF_TYPES (TARIFF_TYPE_ID, CODE, NAME, DESCRIPTION) VALUES
(3, 'WALLET', 'Пополняемый кошелёк',
'Деньги списываются с баланса за каждую поездку. Баланс хранится в поле wallet_balance карты. Можно пополнять.');

-- 7. Карты
CREATE TABLE CARDS (
    CARD_ID BIGSERIAL NOT NULL,
    CARD_GUID UUID NOT NULL UNIQUE,
    CARD_TYPE_ID INT NOT NULL,
    USER_ID BIGINT,
    TRANSPORT_ID BIGINT,
    TARIFF_TYPE_ID INT REFERENCES TARIFF_TYPES(TARIFF_TYPE_ID),
    EXPIRATION_RIDES_PACKAGE TIMESTAMP NOT NULL,
    AVAILABLE_TRAVEL_COUNT INT NOT NULL,
    UNLIMITED_UNTIL_DATE TIMESTAMP,
    WALLET_BALANCE DECIMAL(10, 2),
    UNIQUE_TRAVEL_COUNT INT NOT NULL,
    MAXIMUM_UNIQUE_COUNT INT NOT NULL,
    ISSUE_DATE TIMESTAMP NOT NULL,
    EXPIRATION_DATE TIMESTAMP NOT NULL,
    CONSTRAINT CARDS_pkey PRIMARY KEY (CARD_ID)
);
ALTER SEQUENCE CARDS_CARD_ID_seq
RESTART WITH 1000;

ALTER TABLE CARDS
    ADD CONSTRAINT fk_cards_transport_id
    FOREIGN KEY (TRANSPORT_ID) REFERENCES TRANSPORTS(TRANSPORT_ID);

ALTER TABLE CARDS
    ADD CONSTRAINT fk_cards_card_type_id
    FOREIGN KEY (CARD_TYPE_ID) REFERENCES CARD_TYPES(CARD_TYPE_ID);

ALTER TABLE CARDS
    ADD CONSTRAINT fk_cards_user_id
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

-- CHECK-ограничение для таблицы CARDS
ALTER TABLE CARDS
ADD CONSTRAINT chk_cards_travel_count
CHECK (AVAILABLE_TRAVEL_COUNT >= 0);

-- 8. Чёрный список
CREATE TABLE BLACK_LIST (
    CARD_GUID UUID NOT NULL UNIQUE
);

-- 9. Индексы для производительности
CREATE INDEX idx_cards_guid ON CARDS (CARD_GUID);
CREATE INDEX idx_blacklist_guid ON BLACK_LIST (CARD_GUID);
CREATE INDEX idx_terminals_guid ON TERMINALS (TERMINAL_GUID);